language: r
warnings_are_errors: true
sudo: required
latex: false
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes --no-examples'
addons:
  apt:
    packages:
      # For xml2
      - libcurl14-openssl-dev
      - libxml2-dev
