<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Getting Started • Hurricanes</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-vignette">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../index.html">Hurricanes</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../articles/index.html">Articles</a>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9">
    <div class="page-header toc-ignore">
      <h1>Getting Started</h1>
                        <h4 class="author">Tim Trice</h4>
            
            <h4 class="date">2017-05-19</h4>
          </div>

    
    
<div class="contents">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)</code></pre></div>
<pre><code>## 
## Attaching package: 'dplyr'</code></pre>
<pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(Hurricanes)</code></pre></div>
<div id="general-introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#general-introduction" class="anchor"></a>General Introduction</h2>
<p><code>Hurricanes</code> is intended to give easy access to hurricane archives. In short, it is a web-scraping tool that parses the National Hurricane Center’s (NHC) archives to get storm data.</p>
<p>At this point, data is only available back to 1998.</p>
<p>There are two basins which data is available: north Atlantic (“AL”) and northeastern Pacific (“EP”). The northeastern Pacific basin typically covers from the west coast of North America to -140° longitude (140°W). The Central Pacific Hurricane Center (CPHC) covers the north Pacific from -140° to -180°.</p>
<p>The NHC will stop issuing advisories once a storm crosses -140° where the CPHC takes over. However, I cannot rule out that some storms that have crossed this “boundary” or even developed in CPHC waters will not exist in records retrieved.</p>
<p>On a semi-related note. In some instances (such as Hurricane Otto, 2016) a storm may cross from the Atlantic to Pacific ocean (and even vice versa, though rare). When this happens the storm is given a new name once it emerges into the Pacific ocean. However, if a storm crosses -140° longitude it retains it’s name.</p>
<p>Lastly, it is possible a storm will develop at the end of the year and continue to exist into the next year. I am not aware if those storms will exist in this package as of this time. However, generally the storm should be listed in the archives of the year it developed.</p>
</div>
<div id="get-storms" class="section level2">
<h2 class="hasAnchor">
<a href="#get-storms" class="anchor"></a>Get Storms</h2>
<p>By default, <code>get_storms</code> will return all storms that have developed for the current year in both basins. If no storms have developed, an error will be generated. For this example, we’ll use 2016.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">al<span class="fl">.2016</span> &lt;-<span class="st"> </span><span class="kw"><a href="../reference/get_storms.html">get_storms</a></span>(<span class="dt">year =</span> <span class="dv">2016</span>, <span class="dt">basin =</span> <span class="st">"AL"</span>) %&gt;%<span class="st"> </span>tbl_df %&gt;%<span class="st"> </span><span class="kw">print</span>(<span class="dt">n =</span> <span class="kw">nrow</span>(.))</code></pre></div>
<pre><code>## # A tibble: 16 x 4
##     Year                      Name Basin
##    &lt;dbl&gt;                     &lt;chr&gt; &lt;chr&gt;
##  1  2016            Hurricane Alex    AL
##  2  2016     Tropical Storm Bonnie    AL
##  3  2016      Tropical Storm Colin    AL
##  4  2016   Tropical Storm Danielle    AL
##  5  2016            Hurricane Earl    AL
##  6  2016      Tropical Storm Fiona    AL
##  7  2016          Hurricane Gaston    AL
##  8  2016 Tropical Depression Eight    AL
##  9  2016         Hurricane Hermine    AL
## 10  2016        Tropical Storm Ian    AL
## 11  2016      Tropical Storm Julia    AL
## 12  2016       Tropical Storm Karl    AL
## 13  2016       Tropical Storm Lisa    AL
## 14  2016         Hurricane Matthew    AL
## 15  2016          Hurricane Nicole    AL
## 16  2016            Hurricane Otto    AL
## # ... with 1 more variables: Link &lt;chr&gt;</code></pre>
<p>You can also gather multiple years.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/get_storms.html">get_storms</a></span>(<span class="dt">year =</span> <span class="dv">2014</span>:<span class="dv">2015</span>, <span class="dt">basin =</span> <span class="st">"EP"</span>)</code></pre></div>
</div>
<div id="getting-storm-data" class="section level2">
<h2 class="hasAnchor">
<a href="#getting-storm-data" class="anchor"></a>Getting Storm Data</h2>
<p><code>get_storm_data</code> can be used to retrieve one or multiple products for a specific cyclone.</p>
<p>Load forecast/advisory data for Hurricane Hermine:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">url &lt;-<span class="st"> </span>al<span class="fl">.2016</span> %&gt;%<span class="st"> </span><span class="kw">filter</span>(Name ==<span class="st"> "Hurricane Hermine"</span>) %&gt;%<span class="st"> </span>.$Link
<span class="kw"><a href="../reference/get_storm_data.html">get_storm_data</a></span>(<span class="st">"fstadv"</span>, <span class="dt">link =</span> url)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>This call brings a dataframe to the global environment: <code>fstadv</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(fstadv)</code></pre></div>
<pre><code>## # A tibble: 6 x 125
##        Key   Adv                Date  Name              Status   Lat
##      &lt;chr&gt; &lt;chr&gt;              &lt;dttm&gt; &lt;chr&gt;               &lt;chr&gt; &lt;dbl&gt;
## 1 AL092016     1 2016-08-28 21:00:00  Nine Tropical Depression  23.7
## 2 AL092016     2 2016-08-29 03:00:00  Nine Tropical Depression  23.4
## 3 AL092016     3 2016-08-29 09:00:00  Nine Tropical Depression  23.5
## 4 AL092016     4 2016-08-29 15:00:00  Nine Tropical Depression  23.6
## 5 AL092016     5 2016-08-29 21:00:00  Nine Tropical Depression  24.0
## 6 AL092016     6 2016-08-30 03:00:00  Nine Tropical Depression  23.9
## # ... with 119 more variables: Lon &lt;dbl&gt;, Wind &lt;dbl&gt;, Gust &lt;dbl&gt;,
## #   Pressure &lt;dbl&gt;, PosAcc &lt;dbl&gt;, FwdDir &lt;dbl&gt;, FwdSpeed &lt;dbl&gt;, Eye &lt;dbl&gt;,
## #   NE34 &lt;dbl&gt;, SE34 &lt;dbl&gt;, SW34 &lt;dbl&gt;, NW34 &lt;dbl&gt;, NE50 &lt;dbl&gt;,
## #   SE50 &lt;dbl&gt;, SW50 &lt;dbl&gt;, NW50 &lt;dbl&gt;, NE64 &lt;dbl&gt;, SE64 &lt;dbl&gt;,
## #   SW64 &lt;dbl&gt;, NW64 &lt;dbl&gt;, SeasNE &lt;dbl&gt;, SeasSE &lt;dbl&gt;, SeasSW &lt;dbl&gt;,
## #   SeasNW &lt;dbl&gt;, Hr12FcstDate &lt;dttm&gt;, Hr12Lat &lt;dbl&gt;, Hr12Lon &lt;dbl&gt;,
## #   Hr12Wind &lt;dbl&gt;, Hr12Gust &lt;dbl&gt;, Hr12NE34 &lt;dbl&gt;, Hr12SE34 &lt;dbl&gt;,
## #   Hr12SW34 &lt;dbl&gt;, Hr12NW34 &lt;dbl&gt;, Hr12NE50 &lt;dbl&gt;, Hr12SE50 &lt;dbl&gt;,
## #   Hr12SW50 &lt;dbl&gt;, Hr12NW50 &lt;dbl&gt;, Hr12NE64 &lt;dbl&gt;, Hr12SE64 &lt;dbl&gt;,
## #   Hr12SW64 &lt;dbl&gt;, Hr12NW64 &lt;dbl&gt;, Hr24FcstDate &lt;dttm&gt;, Hr24Lat &lt;dbl&gt;,
## #   Hr24Lon &lt;dbl&gt;, Hr24Wind &lt;dbl&gt;, Hr24Gust &lt;dbl&gt;, Hr24NE34 &lt;dbl&gt;,
## #   Hr24SE34 &lt;dbl&gt;, Hr24SW34 &lt;dbl&gt;, Hr24NW34 &lt;dbl&gt;, Hr24NE50 &lt;dbl&gt;,
## #   Hr24SE50 &lt;dbl&gt;, Hr24SW50 &lt;dbl&gt;, Hr24NW50 &lt;dbl&gt;, Hr24NE64 &lt;dbl&gt;,
## #   Hr24SE64 &lt;dbl&gt;, Hr24SW64 &lt;dbl&gt;, Hr24NW64 &lt;dbl&gt;, Hr36FcstDate &lt;dttm&gt;,
## #   Hr36Lat &lt;dbl&gt;, Hr36Lon &lt;dbl&gt;, Hr36Wind &lt;dbl&gt;, Hr36Gust &lt;dbl&gt;,
## #   Hr36NE34 &lt;dbl&gt;, Hr36SE34 &lt;dbl&gt;, Hr36SW34 &lt;dbl&gt;, Hr36NW34 &lt;dbl&gt;,
## #   Hr36NE50 &lt;dbl&gt;, Hr36SE50 &lt;dbl&gt;, Hr36SW50 &lt;dbl&gt;, Hr36NW50 &lt;dbl&gt;,
## #   Hr36NE64 &lt;dbl&gt;, Hr36SE64 &lt;dbl&gt;, Hr36SW64 &lt;dbl&gt;, Hr36NW64 &lt;dbl&gt;,
## #   Hr48FcstDate &lt;dttm&gt;, Hr48Lat &lt;dbl&gt;, Hr48Lon &lt;dbl&gt;, Hr48Wind &lt;dbl&gt;,
## #   Hr48Gust &lt;dbl&gt;, Hr48NE34 &lt;dbl&gt;, Hr48SE34 &lt;dbl&gt;, Hr48SW34 &lt;dbl&gt;,
## #   Hr48NW34 &lt;dbl&gt;, Hr48NE50 &lt;dbl&gt;, Hr48SE50 &lt;dbl&gt;, Hr48SW50 &lt;dbl&gt;,
## #   Hr48NW50 &lt;dbl&gt;, Hr48NE64 &lt;dbl&gt;, Hr48SE64 &lt;dbl&gt;, Hr48SW64 &lt;dbl&gt;,
## #   Hr48NW64 &lt;dbl&gt;, Hr72FcstDate &lt;dttm&gt;, Hr72Lat &lt;dbl&gt;, Hr72Lon &lt;dbl&gt;,
## #   Hr72Wind &lt;dbl&gt;, Hr72Gust &lt;dbl&gt;, Hr72NE34 &lt;dbl&gt;, Hr72SE34 &lt;dbl&gt;,
## #   Hr72SW34 &lt;dbl&gt;, ...</code></pre>
<p>We can get the forecast/advisory data and wind speed probabilities at once:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/get_storm_data.html">get_storm_data</a></span>(<span class="st">"fstadv"</span>, <span class="st">"wndprb"</span>, <span class="dt">link =</span> url)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>We now have two dataframes in our global environment: <code>fstadv</code> and <code>wndprb</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(fstadv)</code></pre></div>
<pre><code>## [1]  38 125</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(wndprb)</code></pre></div>
<pre><code>## [1] 2251   18</code></pre>
<p>You can pass preferred values for names of each dataframe returned.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/get_storm_data.html">get_storm_data</a></span>(<span class="st">"fstadv"</span>, <span class="st">"wndprb"</span>,
               <span class="dt">names =</span> <span class="kw">list</span>(<span class="st">"fstadv"</span> =<span class="st"> "al.09.2016.fstadv"</span>,
                            <span class="st">"wndprb"</span> =<span class="st"> "al.09.2016.wndprb"</span>),
               <span class="dt">link =</span> url)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(al<span class="fl">.09.2016</span>.fstadv)</code></pre></div>
<pre><code>## [1]  38 125</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(al<span class="fl">.09.2016</span>.wndprb)</code></pre></div>
<pre><code>## [1] 2251   18</code></pre>
</div>
<div id="forecastadvisory-product-fstadv" class="section level2">
<h2 class="hasAnchor">
<a href="#forecastadvisory-product-fstadv" class="anchor"></a>Forecast/Advisory Product (<code>fstadv</code>)</h2>
<p>The core of a storm’s dataset is located in the Forecast/Advisory product. This product contains current location, forecast position, movement and structural detail of the cyclone.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">al<span class="fl">.09.2016</span> &lt;-<span class="st"> </span><span class="kw"><a href="../reference/get_fstadv.html">get_fstadv</a></span>(<span class="dt">link =</span> url)</code></pre></div>
<p>The dataframe returned is rather wide:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(al<span class="fl">.09.2016</span>)</code></pre></div>
<pre><code>## [1]  38 125</code></pre>
<p>There is a function that will break the dataframe down into four narrow frames; each with it’s own purpose. Let’s look at that and then I’ll go over the variables returned.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/fstadv_split.html">fstadv_split</a></span>(<span class="st">"al.09.2016"</span>)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>The <code>fstadv_split</code> function takes the name of the dataframe in character format. The original dataframe is then split up and each “child” dataframe receives the same name with it’s purpose appended to the name. In this instance, <code>al.09.2016</code> remains the parent dataframe but it is much more narrow:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(al<span class="fl">.09.2016</span>)</code></pre></div>
<pre><code>## [1] 38 18</code></pre>
<p>And our child dataframes:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(al<span class="fl">.09.2016</span>.wr)</code></pre></div>
<pre><code>## [1] 49  8</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(al<span class="fl">.09.2016</span>.fst)</code></pre></div>
<pre><code>## [1] 249   8</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(al<span class="fl">.09.2016</span>.fst.wr)</code></pre></div>
<pre><code>## [1] 287   9</code></pre>
<div id="current-details" class="section level3">
<h3 class="hasAnchor">
<a href="#current-details" class="anchor"></a>Current Details</h3>
<p>In this example, <code>al.09.2016</code> is our parent dataframe. It contains the core data for each advisory listed for this particular cyclone.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(al<span class="fl">.09.2016</span>)</code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    38 obs. of  18 variables:
##  $ Key     : chr  "AL092016" "AL092016" "AL092016" "AL092016" ...
##  $ Adv     : chr  "1" "2" "3" "4" ...
##  $ Date    : POSIXct, format: "2016-08-28 21:00:00" "2016-08-29 03:00:00" ...
##  $ Name    : chr  "Nine" "Nine" "Nine" "Nine" ...
##  $ Status  : chr  "Tropical Depression" "Tropical Depression" "Tropical Depression" "Tropical Depression" ...
##  $ Lat     : num  23.7 23.4 23.5 23.6 24 23.9 23.8 24 24.4 24.3 ...
##  $ Lon     : num  -81.7 -82.7 -83.9 -84.3 -84.8 -85.5 -86.6 -87.2 -87.3 -87.8 ...
##  $ Wind    : num  30 30 30 30 30 30 30 30 30 30 ...
##  $ Gust    : num  40 40 40 40 40 40 40 40 40 40 ...
##  $ Pressure: num  1009 1007 1007 1007 1007 ...
##  $ PosAcc  : num  25 25 20 25 25 20 20 25 20 20 ...
##  $ FwdDir  : num  270 270 275 280 290 280 275 290 320 345 ...
##  $ FwdSpeed: num  8 8 8 6 4 6 6 6 4 2 ...
##  $ Eye     : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ SeasNE  : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ SeasSE  : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ SeasSW  : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ SeasNW  : num  NA NA NA NA NA NA NA NA NA NA ...</code></pre>
<p>The variables <code>Key</code>, <code>Adv</code> and <code>Date</code> should be used if you wish to join this parent data frame with any of the child dataframes.</p>
</div>
<div id="wind-radius" class="section level3">
<h3 class="hasAnchor">
<a href="#wind-radius" class="anchor"></a>Wind Radius</h3>
<p>Any cyclone of at least tropical storm-strength will have associated wind field values.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(al<span class="fl">.09.2016</span>.wr)</code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    49 obs. of  8 variables:
##  $ Key      : chr  "AL092016" "AL092016" "AL092016" "AL092016" ...
##  $ Adv      : chr  "13" "14" "14" "15" ...
##  $ Date     : POSIXct, format: "2016-08-31 21:00:00" "2016-09-01 03:00:00" ...
##  $ WindField: num  34 34 50 34 50 34 50 34 50 34 ...
##  $ NE       : num  110 110 20 120 20 120 60 150 100 150 ...
##  $ SE       : num  110 110 20 120 20 120 60 160 120 160 ...
##  $ SW       : num  0 90 0 60 0 60 0 60 30 60 ...
##  $ NW       : num  0 0 0 0 0 40 0 60 30 60 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(al<span class="fl">.09.2016</span>.wr)</code></pre></div>
<pre><code>## # A tibble: 6 x 8
##        Key   Adv                Date WindField    NE    SE    SW    NW
##      &lt;chr&gt; &lt;chr&gt;              &lt;dttm&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 AL092016    13 2016-08-31 21:00:00        34   110   110     0     0
## 2 AL092016    14 2016-09-01 03:00:00        34   110   110    90     0
## 3 AL092016    14 2016-09-01 03:00:00        50    20    20     0     0
## 4 AL092016    15 2016-09-01 09:00:00        34   120   120    60     0
## 5 AL092016    15 2016-09-01 09:00:00        50    20    20     0     0
## 6 AL092016    16 2016-09-01 15:00:00        34   120   120    60    40</code></pre>
<p>In the example above you can see that for advisory #13, this cyclone had one-minute sustained wind speeds of at least 34 kts spread out 110 nautical miles to the northeast of the center of circulation, 110 nautical miles to the southeast, but 0 miles in both the southwest and northwest quadrant. (This is not unusual as many weak cyclones are assymetric in some fashion.)</p>
<p>On advisory #14 there are two rows of data: one for the 34kt wind field and another for the 50kt wind field (a third, 64kt, will be present for hurricanes).</p>
<p>You can identify that on this advisory the storm system has expanded it’s circulation into the southwestern quadrant but still hasn’t wrapped around to encompass the northwestern quadrant. The radius of 50kt winds remains tightly around the center in the eastern quadrant.</p>
<p>Note that if a storm is not of tropical storm-strength, this data will not exist.</p>
</div>
<div id="forecast" class="section level3">
<h3 class="hasAnchor">
<a href="#forecast" class="anchor"></a>Forecast</h3>
<p>Most Forecast/Advisory products will have forecast data associated with it unless the storm is expected to dissipate very soon or already has. This data can be found in <code>al.09.2016.fst</code>.</p>
<p>Each forecast/advisory product can have many (or none) forecast positions. And this number has changed over the years. Originally forecasts were only issued for 72 hours but this has expanded now to 120 hours.</p>
<p>Forecasts exist for every 12-hour period up to 48 hours. After that time, a forecast will be available for sequential 24-hour periods; i.e., 12, 24, 36, 48, 72, 96 and 120.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(al<span class="fl">.09.2016</span>.fst)</code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    249 obs. of  8 variables:
##  $ Key     : chr  "AL092016" "AL092016" "AL092016" "AL092016" ...
##  $ Adv     : chr  "1" "1" "1" "1" ...
##  $ Date    : POSIXct, format: "2016-08-28 21:00:00" "2016-08-28 21:00:00" ...
##  $ FcstDate: POSIXct, format: "2016-08-29 06:00:00" "2016-08-29 18:00:00" ...
##  $ Lat     : num  23.9 24.3 24.6 25.1 26.8 29 31 23.5 23.8 24.4 ...
##  $ Lon     : num  -83.6 -85.4 -86.8 -87.6 -87.4 -84.5 -80 -84 -85.4 -86.8 ...
##  $ Wind    : num  30 35 35 40 45 45 45 30 35 35 ...
##  $ Gust    : num  40 45 45 50 55 55 55 40 45 45 ...</code></pre>
</div>
<div id="forecast-wind-radius" class="section level3">
<h3 class="hasAnchor">
<a href="#forecast-wind-radius" class="anchor"></a>Forecast Wind Radius</h3>
<p>Some forecast positions may also contain wind radius information (only up to 72 hours). This data can be found in <code>al.09.2016.fst.wr</code>. It’s structure is very similar to <code>al.2019.2016.wr</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(al<span class="fl">.09.2016</span>.fst.wr)</code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    287 obs. of  9 variables:
##  $ Key      : chr  "AL092016" "AL092016" "AL092016" "AL092016" ...
##  $ Adv      : chr  "1" "1" "1" "1" ...
##  $ Date     : POSIXct, format: "2016-08-28 21:00:00" "2016-08-28 21:00:00" ...
##  $ FcstDate : POSIXct, format: "2016-08-29 18:00:00" "2016-08-30 06:00:00" ...
##  $ WindField: num  34 34 34 34 34 34 34 34 34 34 ...
##  $ NE       : num  30 30 50 60 30 40 50 60 40 40 ...
##  $ SE       : num  0 0 30 60 0 20 30 50 0 20 ...
##  $ SW       : num  0 0 0 40 0 0 20 30 0 0 ...
##  $ NW       : num  30 30 40 50 30 30 40 50 40 30 ...</code></pre>
<p>You can join this dataframe to <code>al.09.2016.fst</code> by the <code>Key</code>, <code>Adv</code>, <code>Date</code> and <code>FcstDate</code> variables.</p>
<p>Please see the National Hurricane Center’s website for more information on understanding the <a href="http://www.nhc.noaa.gov/help/tcm.shtml?">Forecast/Advisory product</a>.</p>
</div>
</div>
<div id="strike-probabilities-prblty" class="section level2">
<h2 class="hasAnchor">
<a href="#strike-probabilities-prblty" class="anchor"></a>Strike Probabilities (<code>prblty</code>)</h2>
<p>Strike probabilities were discontinued after the 2005 hurricane season. For this example, we’ll look at Hurricane Katrina. For this we use the function <code>get_prblty</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">al<span class="fl">.2005</span> &lt;-<span class="st"> </span><span class="kw"><a href="../reference/get_storms.html">get_storms</a></span>(<span class="dt">year =</span> <span class="dv">2005</span>, <span class="dt">basin =</span> <span class="st">"AL"</span>)

url &lt;-<span class="st"> </span>al<span class="fl">.2005</span> %&gt;%<span class="st"> </span><span class="kw">filter</span>(Name ==<span class="st"> "Hurricane Katrina"</span>) %&gt;%<span class="st"> </span>.$Link

al<span class="fl">.12.2016</span>.prblty &lt;-<span class="st"> </span><span class="kw"><a href="../reference/get_prblty.html">get_prblty</a></span>(<span class="dt">link =</span> url)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(al<span class="fl">.12.2016</span>.prblty)</code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    937 obs. of  10 variables:
##  $ Status  : chr  "Tropical Depression" "Tropical Depression" "Tropical Depression" "Tropical Depression" ...
##  $ Name    : chr  "Twelve" "Twelve" "Twelve" "Twelve" ...
##  $ Adv     : chr  "1" "1" "1" "1" ...
##  $ Date    : POSIXct, format: "2005-08-23 21:00:00" "2005-08-23 21:00:00" ...
##  $ Location: chr  "25.0N  77.7W" "JACKSONVILLE FL" "25.7N  78.5W" "SAVANNAH GA" ...
##  $ A       : num  50 0 36 0 19 0 0 0 0 0 ...
##  $ B       : num  0 0 0 0 6 0 1 0 0 5 ...
##  $ C       : num  0 2 0 0 1 0 0 0 0 3 ...
##  $ D       : num  0 9 1 6 1 3 3 2 2 5 ...
##  $ E       : num  50 11 37 6 27 3 4 2 2 13 ...</code></pre>
<p>This dataframe contains the possibility of a cyclone passing within 65 nautical miles of <code>Location</code>. The variables <code>A</code>, <code>B</code>, <code>C</code>, <code>D</code>, and <code>E</code> are as they appear in the products and were left as-is to avoid confusion. They’re definition is as follows:</p>
<ul>
<li>
<code>A</code> - current through 12 hours.</li>
<li>
<code>B</code> - within the next 12-24 hours</li>
<li>
<code>C</code> - within the next 24-36 hours</li>
<li>
<code>D</code> - within the next 36-48 hours</li>
<li>
<code>E</code> - Total probability from current through 48 hours.</li>
</ul>
<p>Many values in the text product may be “X” for less than 1% chance of a strike. These values are converted to 0 as the fields are numeric.</p>
<p>The strike probability products did not contain <code>Key</code> which is the unique identifier for every cyclone. So the best way to do any joins will be by <code>Name</code>, <code>Adv</code> and <code>Date</code>.</p>
<p>Strike Probabilities may not exist for most Pacific cyclones.</p>
</div>
<div id="wind-speed-probabilities-wndprb" class="section level2">
<h2 class="hasAnchor">
<a href="#wind-speed-probabilities-wndprb" class="anchor"></a>Wind Speed Probabilities (<code>wndprb</code>)</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">url &lt;-<span class="st"> </span>al<span class="fl">.2016</span> %&gt;%<span class="st"> </span><span class="kw">filter</span>(Name ==<span class="st"> "Hurricane Hermine"</span>) %&gt;%<span class="st"> </span>.$Link
al<span class="fl">.09.2016</span>.wndprb &lt;-<span class="st"> </span><span class="kw"><a href="../reference/get_wndprb.html">get_wndprb</a></span>(<span class="dt">link =</span> url)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(al<span class="fl">.09.2016</span>.wndprb)</code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    2251 obs. of  18 variables:
##  $ Key       : chr  "AL092016" "AL092016" "AL092016" "AL092016" ...
##  $ Adv       : chr  "1" "1" "1" "1" ...
##  $ Date      : POSIXct, format: "2016-08-28 21:00:00" "2016-08-28 21:00:00" ...
##  $ Location  : chr  "ELIZABETH CTY" "RALEIGH NC" "ROCKY MT NC" "CAPE HATTERAS" ...
##  $ Wind      : num  34 34 34 34 34 34 34 34 34 34 ...
##  $ Wind12    : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Wind24    : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Wind24Cum : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Wind36    : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Wind36Cum : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Wind48    : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Wind48Cum : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Wind72    : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Wind72Cum : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Wind96    : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Wind96Cum : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Wind120   : num  3 3 3 5 5 3 5 6 6 7 ...
##  $ Wind120Cum: num  3 3 3 5 5 3 5 6 6 7 ...</code></pre>
<p>Wind Speed Probabilities are a bit more advanced than their predecessor. The <code>Wind</code> variable is for 34kt, 50kt and 64kt winds expected within a specific time period.</p>
<p>Each consecutive variable is within a specific time-frame (12, 24, 36, 48, 72, 96 and 120 hours) for both that time frame and cumulative.</p>
<p>For example, <code>Wind24</code> is the chance of <code>Wind</code> between 12-24 hours. <code>Wind24Cum</code> is the cumulative probability from <code>Date</code> through 24 hours.</p>
<p>As with strike probabilities, an “X” in the original text product meant less than 0.5% chance for the specified wind in the specified time period. “X” has been replaced by 0 in this package.</p>
<p>Strike Probabilities may not exist for most Pacific cyclones.</p>
<p>See <a href="http://www.nhc.noaa.gov/about/pdf/About_Windspeed_Probabilities.pdf">Tropical Cyclone Wind Speed Probabilities Products</a> for more information.</p>
</div>
<div id="other-products" class="section level2">
<h2 class="hasAnchor">
<a href="#other-products" class="anchor"></a>Other products</h2>
<p>Other products are available:</p>
<ul>
<li><p><code>get_public</code> for Public Advisory statements. Think general information for the public audience. May not exist for some Pacific cyclones. Additionally, when watches and warnings are issued, these are issued every 3 hours (and, in some cases, every two).</p></li>
<li><p><code>get_discus</code> for Storm Discussions. These are more technical statements on the structure of a storm, forecast model tendencies and satellite presentation.</p></li>
<li><p><code>get_update</code> These are brief update statements when something considerable has changed in the cyclone or if the cyclone is making landfall.</p></li>
<li><p><code>get_posest</code>. Position estimates are generally issued when a storm is making landfall and may be issued hourly.</p></li>
</ul>
<p>Hurricane Ike, 2008, has both updates and position estimates.</p>
<p>At this time none of these products are parsed. Only the content of the product is returned.</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#general-introduction">General Introduction</a></li>
      <li><a href="#get-storms">Get Storms</a></li>
      <li><a href="#getting-storm-data">Getting Storm Data</a></li>
      <li><a href="#forecastadvisory-product-fstadv">Forecast/Advisory Product (<code>fstadv</code>)</a></li>
      <li><a href="#strike-probabilities-prblty">Strike Probabilities (<code>prblty</code>)</a></li>
      <li><a href="#wind-speed-probabilities-wndprb">Wind Speed Probabilities (<code>wndprb</code>)</a></li>
      <li><a href="#other-products">Other products</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Tim Trice.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://hadley.github.io/pkgdown/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  </body>
</html>
