<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Getting Started • rrricanes</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-vignette">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="../index.html">rrricanes</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../articles/index.html">Articles</a>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/timtrice/rrricanes">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9">
    <div class="page-header toc-ignore">
      <h1>Getting Started</h1>
                        <h4 class="author">Tim Trice</h4>
            
            <h4 class="date">2017-06-11</h4>
          </div>

    
    
<div class="contents">
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)</code></pre></div>
<pre><code>## 
## Attaching package: 'dplyr'</code></pre>
<pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(rrricanes)</code></pre></div>
<pre><code>## rrricanes is not intended for use in emergency situations.</code></pre>
<div id="general-introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#general-introduction" class="anchor"></a>General Introduction</h2>
<p><code>rrricanes</code> is intended to give easy access to hurricane archives. It is a web-scraping tool that parses the National Hurricane Center’s (NHC) archives to get storm data. Data is available for storms dating back to 1998.</p>
<p>There are two basins which data is available: north Atlantic (“AL”) and northeastern Pacific (“EP”). The northeastern Pacific basin typically covers from the west coast of North America to -140° longitude (140°W).</p>
</div>
<div id="get-storms" class="section level2">
<h2 class="hasAnchor">
<a href="#get-storms" class="anchor"></a>Get Storms</h2>
<p>By default, <code>get_storms</code> will return all storms that have developed for the current year in both basins. If no storms have developed, an error will be generated. For this example, we’ll use 2012.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">al<span class="fl">.2012</span> &lt;-<span class="st"> </span><span class="kw"><a href="../reference/get_storms.html">get_storms</a></span>(<span class="dt">year =</span> <span class="dv">2012</span>, <span class="dt">basin =</span> <span class="st">"AL"</span>)</code></pre></div>
</div>
<div id="getting-storm-data" class="section level2">
<h2 class="hasAnchor">
<a href="#getting-storm-data" class="anchor"></a>Getting Storm Data</h2>
<p><code>get_storm_data</code> can be used to retrieve one or multiple products for one or more cyclones. A list of dataframes is returned.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">al182012_fstadv &lt;-<span class="st"> </span>al<span class="fl">.2012</span> %&gt;%<span class="st"> </span>
<span class="st">    </span><span class="kw">filter</span>(Name ==<span class="st"> "Hurricane Sandy"</span>) %&gt;%<span class="st"> </span>
<span class="st">    </span>.$Link %&gt;%<span class="st"> </span>
<span class="st">    </span><span class="kw"><a href="../reference/get_storm_data.html">get_storm_data</a></span>(<span class="dt">products =</span> <span class="st">"fstadv"</span>)</code></pre></div>
<p>We can get the forecast/advisory data and wind speed probabilities at once:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">al182012 &lt;-<span class="st"> </span>al<span class="fl">.2012</span> %&gt;%<span class="st"> </span>
<span class="st">    </span><span class="kw">filter</span>(Name ==<span class="st"> "Hurricane Sandy"</span>) %&gt;%<span class="st"> </span>
<span class="st">    </span>.$Link %&gt;%<span class="st"> </span>
<span class="st">    </span><span class="kw"><a href="../reference/get_storm_data.html">get_storm_data</a></span>(<span class="kw">c</span>(<span class="st">"fstadv"</span>, <span class="st">"wndprb"</span>))</code></pre></div>
<p><code>al182012</code> now contains two dataframes for Hurricane Sandy; <code>fstadv</code> and <code>wndprb</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(al182012$fstadv)</code></pre></div>
<pre><code>## [1]  31 149</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(al182012$wndprb)</code></pre></div>
<pre><code>## [1] 2227   18</code></pre>
</div>
<div id="forecastadvisory-product-fstadv" class="section level2">
<h2 class="hasAnchor">
<a href="#forecastadvisory-product-fstadv" class="anchor"></a>Forecast/Advisory Product (<code>fstadv</code>)</h2>
<p>The core of a storm’s dataset is located in the Forecast/Advisory product, <code>fstadv</code>. This product contains current location, forecast position, movement and structural details of the cyclone.</p>
<p>To access only this product, we can use <code>get_fstadv</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">al182012_fstadv &lt;-<span class="st"> </span>al<span class="fl">.2012</span> %&gt;%<span class="st"> </span>
<span class="st">    </span><span class="kw">filter</span>(Name ==<span class="st"> "Hurricane Sandy"</span>) %&gt;%<span class="st"> </span>
<span class="st">    </span>.$Link %&gt;%<span class="st"> </span>
<span class="st">    </span><span class="kw"><a href="../reference/get_fstadv.html">get_fstadv</a></span>()</code></pre></div>
<p>As you may have noticed above, the dataframe is very wide at 149 variables. There are four groups of variables in this dataset: current details, current wind radii, forecast positions, and forecast wind radii.</p>
<div id="current-details" class="section level3">
<h3 class="hasAnchor">
<a href="#current-details" class="anchor"></a>Current Details</h3>
<p>Let’s look at an example of the current details.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(al182012_fstadv %&gt;%<span class="st"> </span><span class="kw">select</span>(Status:Eye, SeasNE:SeasNW))</code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    31 obs. of  18 variables:
##  $ Status  : chr  "Tropical Depression" "Tropical Storm" "Tropical Storm" "Tropical Storm" ...
##  $ Name    : chr  "Eighteen" "Sandy" "Sandy" "Sandy" ...
##  $ Adv     : chr  "1" "2" "3" "4" ...
##  $ Date    : POSIXct, format: "2012-10-22 15:00:00" "2012-10-22 21:00:00" ...
##  $ Key     : chr  "AL182012" "AL182012" "AL182012" "AL182012" ...
##  $ Lat     : num  13.5 12.5 12.7 13.3 13.8 14.3 15.2 16.3 17.1 18.3 ...
##  $ Lon     : num  -78 -78.5 -78.6 -78.6 -77.8 -77.6 -77.2 -77 -76.7 -76.6 ...
##  $ Wind    : num  25 35 40 40 45 45 50 60 70 70 ...
##  $ Gust    : num  35 45 50 50 55 55 60 75 85 85 ...
##  $ Pressure: num  1003 999 998 998 993 ...
##  $ PosAcc  : num  45 50 25 40 30 30 20 20 20 20 ...
##  $ FwdDir  : num  230 NA NA 360 20 20 15 10 15 10 ...
##  $ FwdSpeed: num  4 NA NA 3 4 5 9 12 11 12 ...
##  $ Eye     : num  NA NA NA NA NA NA 25 NA NA NA ...
##  $ SeasNE  : num  NA 60 60 70 75 90 180 180 180 180 ...
##  $ SeasSE  : num  NA 60 45 80 60 90 180 180 240 240 ...
##  $ SeasSW  : num  NA 0 0 0 0 0 0 45 0 0 ...
##  $ SeasNW  : num  NA 0 45 50 50 50 0 100 90 90 ...</code></pre>
<p>The most important variable in this dataset is <code>Key</code>. <code>Key</code> is a unique identifier for each storm that develops in either basin. It is formatted such as “AABBCCCC” where “AA” is the basin abbreviation (AL or EP), “BB” is the year number of the storm left-padded, and “CC” is the year of the storm.</p>
<p><code>Adv</code> is the second-most important variable here. You’ll notice it is in character format. For regularly-scheduled advisories, advisory numbers are always numeric. However, when watches and warnings are in effect, intermediate advisories are issued which are given alpha suffixes; i.e., 1, 2, 3, 3A, 4, 4A, 4B, 5, etc.</p>
<p>Only the Public Advisory (<code>public</code>) will be issued more frequently. All other regular products (<code>discus</code>, <code>fstadv</code>, <code>prblty</code>, <code>wndprb</code>) are generally issued every six hours.</p>
<p><code>Status</code> lists the current designation of the cyclone, i.e., Tropical Depression, Tropical Storm, etc. A <code>Name</code> is given once a storm crosses the threshold of Tropical Storm; that is, winds greater than 33kts.</p>
<p><code>Lat</code> and <code>Lon</code> are the current position of the storm within <code>PosAcc</code> nautical miles. All distance measurements are in nautical miles.</p>
<p><code>Wind</code> and <code>Gust</code> are current one-minute sustained wind speeds in knots (kts). You can use the function <code>knots_to_mph</code> to convert this. All wind speed values are in knots.</p>
<p><code>Pressure</code> is the lowest atmospheric pressure of the cyclone either measured or estimated. It’s value is in millibars but you can use <code><a href="../reference/mb_to_in.html">mb_to_in()</a></code> to convert to inches.</p>
<p><code>FwdDir</code> and <code>FwdSpeed</code> show the compass direction of the forward movement of the cyclone. NA values indicate the storm is stationary or drifting. <code>FwdSpeed</code> is measured in knots.</p>
<p>In some cases, where hurricanes have an identifiable <code>Eye</code>, it’s diameter in nautical miles will also be listed.</p>
<p>Lastly, the <code>Seas</code> variables will exist for a storm of at least tropical storm-strength. This is the distance from the center of circulation that 12ft seas can be found in each quadrant. The measurement is in nautical miles.</p>
<p>Helper function <code>tidy_fstadv</code> will subset this data to a narrow dataframe.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/tidy_fstadv.html">tidy_fstadv</a></span>(al182012_fstadv)</code></pre></div>
<pre><code>## # A tibble: 31 x 18
##         Key   Adv                Date              Status     Name   Lat
##       &lt;chr&gt; &lt;chr&gt;              &lt;dttm&gt;               &lt;chr&gt;    &lt;chr&gt; &lt;dbl&gt;
##  1 AL182012     1 2012-10-22 15:00:00 Tropical Depression Eighteen  13.5
##  2 AL182012     2 2012-10-22 21:00:00      Tropical Storm    Sandy  12.5
##  3 AL182012     3 2012-10-23 03:00:00      Tropical Storm    Sandy  12.7
##  4 AL182012     4 2012-10-23 09:00:00      Tropical Storm    Sandy  13.3
##  5 AL182012     5 2012-10-23 15:00:00      Tropical Storm    Sandy  13.8
##  6 AL182012     6 2012-10-23 21:00:00      Tropical Storm    Sandy  14.3
##  7 AL182012     7 2012-10-24 03:00:00      Tropical Storm    Sandy  15.2
##  8 AL182012     8 2012-10-24 09:00:00      Tropical Storm    Sandy  16.3
##  9 AL182012     9 2012-10-24 15:00:00           Hurricane    Sandy  17.1
## 10 AL182012    10 2012-10-24 21:00:00           Hurricane    Sandy  18.3
## # ... with 21 more rows, and 12 more variables: Lon &lt;dbl&gt;, Wind &lt;dbl&gt;,
## #   Gust &lt;dbl&gt;, Pressure &lt;dbl&gt;, PosAcc &lt;dbl&gt;, FwdDir &lt;dbl&gt;,
## #   FwdSpeed &lt;dbl&gt;, Eye &lt;dbl&gt;, SeasNE &lt;dbl&gt;, SeasSE &lt;dbl&gt;, SeasSW &lt;dbl&gt;,
## #   SeasNW &lt;dbl&gt;</code></pre>
</div>
<div id="wind-radius" class="section level3">
<h3 class="hasAnchor">
<a href="#wind-radius" class="anchor"></a>Wind Radius</h3>
<p>Any cyclone of at least tropical storm-strength will have associated wind radius values. This is the distance from the center of circulation that a specified wind speed (34kts, 50kts, 64kts) can be found in each quadrant. Measurement is in nautical miles.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(al182012_fstadv %&gt;%<span class="st"> </span><span class="kw">select</span>(NE64:NW34))</code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    31 obs. of  12 variables:
##  $ NE64: num  NA NA NA NA NA NA NA NA 20 25 ...
##  $ SE64: num  NA NA NA NA NA NA NA NA 20 20 ...
##  $ SW64: num  NA NA NA NA NA NA NA NA 0 0 ...
##  $ NW64: num  NA NA NA NA NA NA NA NA 0 0 ...
##  $ NE50: num  NA NA NA NA NA NA 0 50 50 50 ...
##  $ SE50: num  NA NA NA NA NA NA 80 70 60 60 ...
##  $ SW50: num  NA NA NA NA NA NA 0 0 30 40 ...
##  $ NW50: num  NA NA NA NA NA NA 0 0 30 40 ...
##  $ NE34: num  NA 50 50 70 70 80 90 100 110 110 ...
##  $ SE34: num  NA 60 60 80 80 90 120 120 120 120 ...
##  $ SW34: num  NA 0 0 0 0 0 0 45 60 70 ...
##  $ NW34: num  NA 0 0 0 0 0 30 45 60 60 ...</code></pre>
<p>A helper function, <code>tidy_wr</code> will reorganize this data into a narrow format and tidied up. Complete wind radius values that are NA are removed for efficiency.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/tidy_wr.html">tidy_wr</a></span>(al182012_fstadv)</code></pre></div>
<pre><code>## # A tibble: 77 x 8
##         Key   Adv                Date WindField    NE    SE    SW    NW
##       &lt;chr&gt; &lt;chr&gt;              &lt;dttm&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 AL182012     2 2012-10-22 21:00:00        34    50    60     0     0
##  2 AL182012     3 2012-10-23 03:00:00        34    50    60     0     0
##  3 AL182012     4 2012-10-23 09:00:00        34    70    80     0     0
##  4 AL182012     5 2012-10-23 15:00:00        34    70    80     0     0
##  5 AL182012     6 2012-10-23 21:00:00        34    80    90     0     0
##  6 AL182012     7 2012-10-24 03:00:00        34    90   120     0    30
##  7 AL182012     7 2012-10-24 03:00:00        50     0    80     0     0
##  8 AL182012     8 2012-10-24 09:00:00        34   100   120    45    45
##  9 AL182012     8 2012-10-24 09:00:00        50    50    70     0     0
## 10 AL182012     9 2012-10-24 15:00:00        34   110   120    60    60
## # ... with 67 more rows</code></pre>
</div>
<div id="forecast" class="section level3">
<h3 class="hasAnchor">
<a href="#forecast" class="anchor"></a>Forecast</h3>
<p>Most Forecast/Advisory products will have forecast data associated with it unless the storm has dissipated or is no longer tropical. There may be up to seven forecast positions. These positions are issued by 12-hour intervals through 48 hours where they are then at 24-hour intervals; 12, 24, 36, 48, 72, 96 and 120 hours.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(al182012_fstadv %&gt;%<span class="st"> </span><span class="kw">select</span>(Hr12FcstDate:Hr12Gust))</code></pre></div>
<p>Notice each variable begins with the prefix “Hrn” where n is the forecast period as noted above. Only Date, Lat, Lon, Wind, Gust and wind radius (will discuss shortly) are given for forecast periods.</p>
<p>Use <code>tidy_fcst</code> to tidy forecast data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/tidy_fcst.html">tidy_fcst</a></span>(al182012_fstadv)</code></pre></div>
<pre><code>## # A tibble: 186 x 8
##         Key   Adv                Date            FcstDate   Lat   Lon
##       &lt;chr&gt; &lt;chr&gt;              &lt;dttm&gt;              &lt;dttm&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 AL182012     1 2012-10-22 15:00:00 2012-10-23 00:00:00  13.7 -78.3
##  2 AL182012     1 2012-10-22 15:00:00 2012-10-23 12:00:00  14.3 -78.1
##  3 AL182012     1 2012-10-22 15:00:00 2012-10-24 00:00:00  15.7 -77.6
##  4 AL182012     1 2012-10-22 15:00:00 2012-10-24 12:00:00  17.4 -77.0
##  5 AL182012     1 2012-10-22 15:00:00 2012-10-25 12:00:00  20.5 -76.0
##  6 AL182012     1 2012-10-22 15:00:00 2012-10-26 12:00:00  24.5 -74.5
##  7 AL182012     2 2012-10-22 21:00:00 2012-10-23 06:00:00  13.6 -78.5
##  8 AL182012     2 2012-10-22 21:00:00 2012-10-23 18:00:00  14.9 -78.3
##  9 AL182012     2 2012-10-22 21:00:00 2012-10-24 06:00:00  16.4 -77.8
## 10 AL182012     2 2012-10-22 21:00:00 2012-10-24 18:00:00  18.2 -77.2
## # ... with 176 more rows, and 2 more variables: Wind &lt;dbl&gt;, Gust &lt;dbl&gt;</code></pre>
<div id="forecast-datestimes" class="section level4">
<h4 class="hasAnchor">
<a href="#forecast-datestimes" class="anchor"></a>Forecast Dates/Times</h4>
<p>A note about forecast times.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">al182012_fstadv %&gt;%<span class="st"> </span><span class="kw">select</span>(Date, Hr12FcstDate) %&gt;%<span class="st"> </span><span class="kw">slice</span>(<span class="dv">1</span>)</code></pre></div>
<pre><code>## # A tibble: 1 x 2
##                  Date Hr12FcstDate
##                &lt;dttm&gt;       &lt;dttm&gt;
## 1 2012-10-22 15:00:00   2012-10-23</code></pre>
<p>Notice the <code>Date</code> of this advisory is Oct 22 at 15:00 UTC. The <code>Hr12FcstDate</code> is Oct 23, 00:00 UTC. This difference, obviously, is not 12 hours. What gives? Forecast/Advisory products are issued with two “current” positions: one that is current (and provided in the dataset) and a position from three hours prior. So, in this specific advisory the text would contain the position of the storm for Oct 22, 12:00 UTC. It is from this position the forecast points are based. I do not know why.</p>
<p>Therefore, while officially the forecast periods are 12, 24, 36, … hours, in reality they are 9, 21, 33, … hours from the issuance time of the product.</p>
</div>
</div>
<div id="forecast-wind-radius" class="section level3">
<h3 class="hasAnchor">
<a href="#forecast-wind-radius" class="anchor"></a>Forecast Wind Radius</h3>
<p>Some forecast positions may also contain wind radius information (only up to 72 hours).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(al182012_fstadv %&gt;%<span class="st"> </span><span class="kw">select</span>(Hr12NE64:Hr12NW34))</code></pre></div>
<p>Again, these variables are prepended with the prefix prefix “Hrn” where n notes the forecast period.</p>
<p><code>tidy_fcst_wr</code> will tidy this subset of data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/tidy_fcst_wr.html">tidy_fcst_wr</a></span>(al182012_fstadv)</code></pre></div>
<pre><code>## # A tibble: 337 x 9
##         Key   Adv                Date            FcstDate WindField    NE
##       &lt;chr&gt; &lt;chr&gt;              &lt;dttm&gt;              &lt;dttm&gt;     &lt;dbl&gt; &lt;dbl&gt;
##  1 AL182012     1 2012-10-22 15:00:00 2012-10-23 00:00:00        34    40
##  2 AL182012     1 2012-10-22 15:00:00 2012-10-23 12:00:00        34    50
##  3 AL182012     1 2012-10-22 15:00:00 2012-10-24 00:00:00        34    80
##  4 AL182012     1 2012-10-22 15:00:00 2012-10-24 00:00:00        50    30
##  5 AL182012     1 2012-10-22 15:00:00 2012-10-24 12:00:00        34    90
##  6 AL182012     1 2012-10-22 15:00:00 2012-10-24 12:00:00        50    40
##  7 AL182012     1 2012-10-22 15:00:00 2012-10-25 12:00:00        34   200
##  8 AL182012     1 2012-10-22 15:00:00 2012-10-25 12:00:00        50    50
##  9 AL182012     2 2012-10-22 21:00:00 2012-10-23 06:00:00        34    50
## 10 AL182012     2 2012-10-22 21:00:00 2012-10-23 18:00:00        34    50
## # ... with 327 more rows, and 3 more variables: SE &lt;dbl&gt;, SW &lt;dbl&gt;,
## #   NW &lt;dbl&gt;</code></pre>
<p>Please see the National Hurricane Center’s website for more information on understanding the <a href="http://www.nhc.noaa.gov/help/tcm.shtml?">Forecast/Advisory product</a>.</p>
</div>
</div>
<div id="strike-probabilities-prblty" class="section level2">
<h2 class="hasAnchor">
<a href="#strike-probabilities-prblty" class="anchor"></a>Strike Probabilities (<code>prblty</code>)</h2>
<p>Strike probabilities were discontinued after the 2005 hurricane season (replaced by Wind Speed Probabilities; <code>wndprb</code>). For this example, we’ll look at Hurricane Katrina. For this we use the function <code>get_prblty</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">al122005_prblty &lt;-<span class="st"> </span><span class="kw"><a href="../reference/get_storms.html">get_storms</a></span>(<span class="dt">year =</span> <span class="dv">2005</span>, <span class="dt">basin =</span> <span class="st">"AL"</span>) %&gt;%<span class="st"> </span>
<span class="st">    </span><span class="kw">filter</span>(Name ==<span class="st"> "Hurricane Katrina"</span>) %&gt;%<span class="st"> </span>
<span class="st">    </span>.$Link %&gt;%<span class="st"> </span>
<span class="st">    </span><span class="kw"><a href="../reference/get_prblty.html">get_prblty</a></span>()</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(al122005_prblty)</code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    937 obs. of  10 variables:
##  $ Status  : chr  "Tropical Depression" "Tropical Depression" "Tropical Depression" "Tropical Depression" ...
##  $ Name    : chr  "Twelve" "Twelve" "Twelve" "Twelve" ...
##  $ Adv     : chr  "1" "1" "1" "1" ...
##  $ Date    : POSIXct, format: "2005-08-23 21:00:00" "2005-08-23 21:00:00" ...
##  $ Location: chr  "25.0N  77.7W" "JACKSONVILLE FL" "25.7N  78.5W" "SAVANNAH GA" ...
##  $ A       : num  50 0 36 0 19 0 0 0 0 0 ...
##  $ B       : num  0 0 0 0 6 0 1 0 0 5 ...
##  $ C       : num  0 2 0 0 1 0 0 0 0 3 ...
##  $ D       : num  0 9 1 6 1 3 3 2 2 5 ...
##  $ E       : num  50 11 37 6 27 3 4 2 2 13 ...</code></pre>
<p>This dataframe contains the possibility of a cyclone passing within 65 nautical miles of <code>Location</code>. The variables <code>A</code>, <code>B</code>, <code>C</code>, <code>D</code>, and <code>E</code> are as they appear in the products and were left as-is to avoid confusion. They’re definition is as follows:</p>
<ul>
<li>
<code>A</code> - current through 12 hours.</li>
<li>
<code>B</code> - within the next 12-24 hours</li>
<li>
<code>C</code> - within the next 24-36 hours</li>
<li>
<code>D</code> - within the next 36-48 hours</li>
<li>
<code>E</code> - Total probability from current through 48 hours.</li>
</ul>
<p>Many values in the text product may be “X” for less than 1% chance of a strike. These values are converted to 0 as the fields are numeric.</p>
<p>The strike probability products did not contain <code>Key</code> which is the unique identifier for every cyclone. So the best way to do any joins will be by <code>Name</code>, <code>Adv</code> and <code>Date</code>.</p>
<p>Strike Probabilities may not exist for most Pacific cyclones.</p>
</div>
<div id="wind-speed-probabilities-wndprb" class="section level2">
<h2 class="hasAnchor">
<a href="#wind-speed-probabilities-wndprb" class="anchor"></a>Wind Speed Probabilities (<code>wndprb</code>)</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">al122005_wndprb &lt;-<span class="st"> </span>al<span class="fl">.2012</span> %&gt;%<span class="st"> </span>
<span class="st">    </span><span class="kw">filter</span>(Name ==<span class="st"> "Hurricane Sandy"</span>) %&gt;%<span class="st"> </span>
<span class="st">    </span>.$Link %&gt;%<span class="st"> </span>
<span class="st">    </span><span class="kw"><a href="../reference/get_wndprb.html">get_wndprb</a></span>()</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(al122005_wndprb)</code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    2227 obs. of  18 variables:
##  $ Key       : chr  "AL182012" "AL182012" "AL182012" "AL182012" ...
##  $ Adv       : chr  "1" "1" "1" "1" ...
##  $ Date      : POSIXct, format: "2012-10-22 15:00:00" "2012-10-22 15:00:00" ...
##  $ Location  : chr  "FT PIERCE FL" "W PALM BEACH" "MIAMI FL" "MARATHON FL" ...
##  $ Wind      : num  34 34 34 34 34 34 34 50 64 34 ...
##  $ Wind12    : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ Wind24    : num  0 0 0 0 1 0 0 0 0 0 ...
##  $ Wind24Cum : num  0 0 0 0 1 0 0 0 0 0 ...
##  $ Wind36    : num  0 0 0 0 1 0 0 0 0 0 ...
##  $ Wind36Cum : num  0 0 0 0 2 0 0 0 0 0 ...
##  $ Wind48    : num  0 0 0 0 1 0 0 0 0 0 ...
##  $ Wind48Cum : num  0 0 0 0 3 0 0 0 0 0 ...
##  $ Wind72    : num  0 0 0 0 0 0 3 0 0 5 ...
##  $ Wind72Cum : num  0 0 0 0 3 0 3 0 0 5 ...
##  $ Wind96    : num  1 2 3 2 0 5 10 3 1 12 ...
##  $ Wind96Cum : num  1 2 3 2 3 5 13 3 1 17 ...
##  $ Wind120   : num  2 2 1 1 0 3 5 2 0 3 ...
##  $ Wind120Cum: num  3 4 4 3 3 8 18 5 1 20 ...</code></pre>
<p>Wind Speed Probabilities are a bit more advanced than their predecessor. The <code>Wind</code> variable is for 34kt, 50kt and 64kt winds expected within a specific time period.</p>
<p>Each consecutive variable is within a specific time-frame (12, 24, 36, 48, 72, 96 and 120 hours) for both that time frame and cumulative.</p>
<p>For example, <code>Wind24</code> is the chance of <code>Wind</code> between 12-24 hours. <code>Wind24Cum</code> is the cumulative probability from <code>Date</code> through 24 hours.</p>
<p>As with strike probabilities, an “X” in the original text product meant less than 0.5% chance for the specified wind in the specified time period. “X” has been replaced by 0 in this package.</p>
<p>Wind Speed Probabilities may not exist for most Pacific cyclones.</p>
<p>See <a href="http://www.nhc.noaa.gov/about/pdf/About_Windspeed_Probabilities.pdf">Tropical Cyclone Wind Speed Probabilities Products</a> for more information.</p>
</div>
<div id="other-products" class="section level2">
<h2 class="hasAnchor">
<a href="#other-products" class="anchor"></a>Other products</h2>
<p>Other products are available:</p>
<ul>
<li><p><code>get_public</code> for Public Advisory statements. Think general information for the public audience. May not exist for some Pacific cyclones. Additionally, when watches and warnings are issued, these are issued every 3 hours (and, in some cases, every two).</p></li>
<li><p><code>get_discus</code> for Storm Discussions. These are more technical statements on the structure of a storm, forecast model tendencies and satellite presentation.</p></li>
<li><p><code>get_update</code> These are brief update statements when something considerable has changed in the cyclone or if the cyclone is making landfall.</p></li>
<li><p><code>get_posest</code>. Position estimates are generally issued when a storm is making landfall and may be issued hourly.</p></li>
</ul>
<p>Hurricane Ike, 2008, has both updates and position estimates.</p>
<p>At this time none of these products are parsed. Only the content of the product is returned.</p>
</div>
<div id="a-faster-alternative" class="section level2">
<h2 class="hasAnchor">
<a href="#a-faster-alternative" class="anchor"></a>A Faster Alternative</h2>
<p>Scraping the data from the NHC archives may be time-consuming for those with “slow” internet connections. Additionally, sometimes the NHC archives <a href="https://github.com/timtrice/rrricanes/issues/66">just aren’t available for some reason</a>.</p>
<p>An alternative method of getting data is by the use of <code>load_storm_data</code>. This function accesses the <code>rrricanesdata</code> repository and returns post-scraped datasets.</p>
<p>Do not assume this data is complete. <code>discus</code>, <code>public</code> and many <code>prblty</code> or <code>wndprb</code> products are not available. However, most <code>fstadv</code> products do exist.</p>
<p>Additionally, please do not assume it will be up-to-date. I will make every effort to keep it as up-to-date as possible. Use the above-mentioned functions for more timely data, if need be.</p>
<p>Let’s load the annual data for both Atlantic and Pacific storms for 2016.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/load_storm_data.html">load_storm_data</a></span>(<span class="dt">years =</span> <span class="dv">2016</span>, <span class="dt">basins =</span> <span class="st">"AL"</span>)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>There are now two datasets in your global environment: <code>AL2016</code> and <code>EP2016</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(AL2016)</code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    17 obs. of  5 variables:
##  $ Key      : chr  "AL012016" "AL022016" "AL032016" "AL042016" ...
##  $ Name     : chr  "Alex" "Bonnie" "Colin" "Danielle" ...
##  $ Wind     : int  75 40 50 40 65 45 105 30 70 55 ...
##  $ StartDate: POSIXct, format: "2016-01-13 21:00:00" "2016-05-27 21:00:00" ...
##  $ EndDate  : POSIXct, format: "2016-01-15 21:00:00" "2016-06-05 03:00:00" ...</code></pre>
<p>This summary data is a little bit different than that obtained through <code>get_storms</code> in that it already has <code>Key</code>, maximum <code>Wind</code> value, <code>StartDate</code> and <code>EndDate</code>.</p>
<p>You can load <code>fstadv</code> products for 2016 as well by passing the <code>products</code> parameter:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/load_storm_data.html">load_storm_data</a></span>(<span class="dt">years =</span> <span class="dv">2016</span>, <span class="dt">basins =</span> <span class="st">"AL"</span>, <span class="dt">products =</span> <span class="st">"fstadv"</span>)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(AL2016_fstadv)</code></pre></div>
<pre><code>## Classes 'tbl_df', 'tbl' and 'data.frame':    427 obs. of  149 variables:
##  $ Status       : chr  "Tropical Storm" "Tropical Storm" "Tropical Storm" "Hurricane" ...
##  $ Name         : chr  "Alex" "Alex" "Alex" "Alex" ...
##  $ Adv          : int  1 2 3 4 5 6 NA 8 9 1 ...
##  $ Date         : POSIXct, format: "2016-01-13 21:00:00" "2016-01-14 03:00:00" ...
##  $ Key          : chr  "AL012016" "AL012016" "AL012016" "AL012016" ...
##  $ Lat          : num  27.1 28.7 30.1 31.5 33.6 34.7 36.8 39.3 43 28.5 ...
##  $ Lon          : num  -30.8 -30 -29.3 -28.4 -27.8 -27.6 -27 -27 -27.8 -74.7 ...
##  $ Wind         : int  45 50 60 75 75 70 65 60 60 30 ...
##  $ Gust         : int  55 60 75 90 90 85 80 75 75 40 ...
##  $ Pressure     : num  990 988 984 981 981 ...
##  $ PosAcc       : int  25 25 25 20 20 20 20 20 30 25 ...
##  $ FwdDir       : int  55 35 20 20 15 10 5 360 350 300 ...
##  $ FwdSpeed     : int  12 15 16 17 20 19 20 24 35 11 ...
##  $ Eye          : int  NA NA 15 15 20 NA NA NA NA NA ...
##  $ NE64         : int  NA NA NA 20 20 20 20 NA NA NA ...
##  $ SE64         : int  NA NA NA 20 20 20 20 NA NA NA ...
##  $ SW64         : int  NA NA NA 0 0 0 0 NA NA NA ...
##  $ NW64         : int  NA NA NA 0 0 0 0 NA NA NA ...
##  $ NE50         : int  NA 0 30 30 40 40 50 150 300 NA ...
##  $ SE50         : int  NA 30 30 40 60 60 50 150 120 NA ...
##  $ SW50         : int  NA 0 0 30 30 30 30 30 30 NA ...
##  $ NW50         : int  NA 0 0 20 40 40 40 40 40 NA ...
##  $ NE34         : int  60 60 120 120 150 150 180 400 420 NA ...
##  $ SE34         : int  120 120 130 130 150 150 150 300 420 NA ...
##  $ SW34         : int  120 120 100 100 100 100 100 180 240 NA ...
##  $ NW34         : int  0 0 30 50 100 100 100 150 120 NA ...
##  $ SeasNE       : int  420 60 300 360 360 360 400 360 360 120 ...
##  $ SeasSE       : int  270 150 300 360 360 360 360 360 540 0 ...
##  $ SeasSW       : int  420 120 150 140 300 300 240 240 300 0 ...
##  $ SeasNW       : int  720 0 240 330 360 360 240 360 360 60 ...
##  $ Hr12FcstDate : POSIXct, format: "2016-01-14 06:00:00" "2016-01-14 12:00:00" ...
##  $ Hr12Lat      : num  28.9 30.6 32.4 34.3 36.4 38.4 41.4 45.1 49.2 29.5 ...
##  $ Hr12Lon      : num  -29.7 -28.8 -28.3 -27.7 -27.5 -27.8 -27.7 -28.3 -29.4 -76.4 ...
##  $ Hr12Wind     : int  45 50 60 80 75 65 65 65 65 35 ...
##  $ Hr12Gust     : int  55 60 75 100 90 80 80 80 80 45 ...
##  $ Hr12NE64     : int  NA NA NA 20 40 50 50 150 150 NA ...
##  $ Hr12SE64     : int  NA NA NA 20 20 20 30 0 0 NA ...
##  $ Hr12SW64     : int  NA NA NA 0 0 0 0 0 0 NA ...
##  $ Hr12NW64     : int  NA NA NA 0 0 0 0 0 0 NA ...
##  $ Hr12NE50     : int  NA 30 30 40 100 100 100 240 300 NA ...
##  $ Hr12SE50     : int  NA 30 30 60 100 100 100 120 120 NA ...
##  $ Hr12SW50     : int  NA 0 0 30 30 30 30 0 0 NA ...
##  $ Hr12NW50     : int  NA 0 0 40 40 40 40 60 0 NA ...
##  $ Hr12NE34     : int  60 60 120 150 200 200 250 420 420 50 ...
##  $ Hr12SE34     : int  120 120 130 150 200 200 250 420 420 0 ...
##  $ Hr12SW34     : int  120 120 100 100 120 120 120 240 240 0 ...
##  $ Hr12NW34     : int  0 0 30 100 120 120 120 180 120 50 ...
##  $ Hr24FcstDate : POSIXct, format: "2016-01-14 18:00:00" "2016-01-15 00:00:00" ...
##  $ Hr24Lat      : num  32 34.2 36.4 38.9 41.8 45 48.7 52.7 56.3 30.7 ...
##  $ Hr24Lon      : num  -28.2 -27.7 -27.6 -27.7 -27.9 -29.1 -30 -31.8 -36.1 -78.3 ...
##  $ Hr24Wind     : int  45 50 60 75 70 65 65 65 65 40 ...
##  $ Hr24Gust     : int  55 60 75 90 85 80 80 80 80 50 ...
##  $ Hr24NE64     : int  NA NA NA 30 90 90 120 120 150 NA ...
##  $ Hr24SE64     : int  NA NA NA 30 0 0 0 0 0 NA ...
##  $ Hr24SW64     : int  NA NA NA 0 0 0 0 0 0 NA ...
##  $ Hr24NW64     : int  NA NA NA 0 0 0 0 0 0 NA ...
##  $ Hr24NE50     : int  NA 40 40 120 240 240 240 240 240 NA ...
##  $ Hr24SE50     : int  NA 40 40 120 180 180 120 150 180 NA ...
##  $ Hr24SW50     : int  NA 0 0 30 0 0 0 0 0 NA ...
##  $ Hr24NW50     : int  NA 0 0 90 60 60 0 0 0 NA ...
##  $ Hr24NE34     : int  100 120 150 240 420 420 420 420 420 60 ...
##  $ Hr24SE34     : int  120 180 190 200 420 420 360 300 360 40 ...
##  $ Hr24SW34     : int  120 120 120 120 120 120 300 240 240 0 ...
##  $ Hr24NW34     : int  60 60 50 180 180 180 120 180 240 60 ...
##  $ Hr36FcstDate : POSIXct, format: "2016-01-15 06:00:00" "2016-01-15 12:00:00" ...
##  $ Hr36Lat      : num  36.3 39.3 42 45.3 49.5 52.7 56 57 56.5 32 ...
##  $ Hr36Lon      : num  -27.5 -27.7 -28.2 -28.6 -29.7 -32.1 -34.5 -40 -47 -79.7 ...
##  $ Hr36Wind     : int  45 55 60 60 65 65 65 55 60 40 ...
##  $ Hr36Gust     : int  55 65 75 75 80 80 80 65 75 50 ...
##  $ Hr36NE64     : int  NA NA NA NA 120 120 120 NA NA NA ...
##  $ Hr36SE64     : int  NA NA NA NA 0 0 0 NA NA NA ...
##  $ Hr36SW64     : int  NA NA NA NA 0 0 0 NA NA NA ...
##  $ Hr36NW64     : int  NA NA NA NA 0 0 0 NA NA NA ...
##  $ Hr36NE50     : int  NA 90 130 210 240 240 300 0 240 NA ...
##  $ Hr36SE50     : int  NA 60 90 150 240 240 0 0 0 NA ...
##  $ Hr36SW50     : int  NA 0 0 0 100 0 0 0 0 NA ...
##  $ Hr36NW50     : int  NA 0 0 120 100 0 300 240 180 NA ...
##  $ Hr36NE34     : int  150 180 360 420 420 420 420 420 420 60 ...
##  $ Hr36SE34     : int  150 240 240 480 480 480 360 60 180 40 ...
##  $ Hr36SW34     : int  100 100 90 180 270 240 180 60 60 0 ...
##  $ Hr36NW34     : int  100 120 60 300 240 240 420 300 300 60 ...
##  $ Hr48FcstDate : POSIXct, format: "2016-01-15 18:00:00" "2016-01-16 00:00:00" ...
##  $ Hr48Lat      : num  42.3 45.7 49.1 53 56.5 59 56.5 NA NA 32.8 ...
##  $ Hr48Lon      : num  -28.2 -29.1 -29.7 -31.5 -34 -37 -47 NA NA -80.2 ...
##  $ Hr48Wind     : int  50 55 60 60 60 65 65 NA NA 40 ...
##  $ Hr48Gust     : int  60 65 75 75 75 80 80 NA NA 50 ...
##  $ Hr48NE64     : chr  NA NA NA NA ...
##  $ Hr48SE64     : chr  NA NA NA NA ...
##  $ Hr48SW64     : chr  NA NA NA NA ...
##  $ Hr48NW64     : chr  NA NA NA NA ...
##  $ Hr48NE50     : int  100 240 240 240 240 240 240 NA NA NA ...
##  $ Hr48SE50     : int  100 60 120 150 240 180 0 NA NA NA ...
##  $ Hr48SW50     : int  0 0 0 0 100 0 0 NA NA NA ...
##  $ Hr48NW50     : int  100 0 0 150 240 240 240 NA NA NA ...
##  $ Hr48NE34     : int  180 420 360 420 420 420 360 NA NA 60 ...
##  $ Hr48SE34     : int  180 360 240 660 300 300 0 NA NA 40 ...
##  $ Hr48SW34     : int  100 60 90 240 180 180 180 NA NA 0 ...
##  $ Hr48NW34     : int  150 120 60 270 420 420 300 NA NA 20 ...
##  $ Hr72FcstDate : POSIXct, format: "2016-01-16 18:00:00" "2016-01-17 00:00:00" ...
##   [list output truncated]</code></pre>
<p>This dataset is the exact same as that returned by <code>get_fstadv</code>. The difference is that it contains all storms for 2017. Use <code>dplyr::filter()</code> if you wish to isolate a specific storm.</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#general-introduction">General Introduction</a></li>
      <li><a href="#get-storms">Get Storms</a></li>
      <li><a href="#getting-storm-data">Getting Storm Data</a></li>
      <li><a href="#forecastadvisory-product-fstadv">Forecast/Advisory Product (<code>fstadv</code>)</a></li>
      <li><a href="#strike-probabilities-prblty">Strike Probabilities (<code>prblty</code>)</a></li>
      <li><a href="#wind-speed-probabilities-wndprb">Wind Speed Probabilities (<code>wndprb</code>)</a></li>
      <li><a href="#other-products">Other products</a></li>
      <li><a href="#a-faster-alternative">A Faster Alternative</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Tim Trice.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://hadley.github.io/pkgdown/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  </body>
</html>
