<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GIS data • rrricanes</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="GIS data">
<meta property="og:description" content="">
<meta property="og:image" content="https://ropensci.github.io/rrricanes/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">rrricanes</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.2.0.6.9001</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/accumulated_cyclone_energy.html">Accumulated Cyclone Energy (ACE)</a>
    </li>
    <li>
      <a href="../articles/forecast_advisory.html">Forecast/Advisory GIS</a>
    </li>
    <li>
      <a href="../articles/getting_started.html">Getting Started</a>
    </li>
    <li>
      <a href="../articles/gis_data.html">GIS data</a>
    </li>
    <li>
      <a href="../articles/installing_rrricanesdata.html">Installing rrricanesdata</a>
    </li>
    <li>
      <a href="../articles/probabilistic_storm_surge.html">Probabilistic Storm Surge</a>
    </li>
    <li>
      <a href="../articles/wind_pressure.html">Wind and Pressure</a>
    </li>
    <li>
      <a href="../articles/wind_speed_probabilities.html">Wind Speed Probabilities</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/ropensci/rrricanes">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>GIS data</h1>
                        <h4 class="author">Tim Trice</h4>
            
            <h4 class="date">2019-06-16</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/ropensci/rrricanes/blob/master/vignettes/gis_data.Rmd"><code>vignettes/gis_data.Rmd</code></a></small>
      <div class="hidden name"><code>gis_data.Rmd</code></div>

    </div>

    
    
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(dplyr)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(rrricanes)</a>
<a class="sourceLine" id="cb1-4" data-line-number="4"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(sf)</a></code></pre></div>
<p>Most storms will contain a variation of GIS datasets that can be plotted with <code>ggplot2</code>. The helper functions for this have the prefix ‘gis’.</p>
<p><strong>All products are experimental and there maybe fluctuations particularly in current datasets.</strong></p>
<p>In general, datasets are available for storms dated back to 1998. However, products such as Wind Speed Probabilities only go back to 1999.</p>
<p>Some datasets require the use of the storm key and an optional advisory. Other products require a datetime value and cannot be isolated by storm key or advisory. The datetime values are not based on the issue time of the advisory, but rather three hours prior. For example, if you are seeking a dataset where the forecast/advisory was issued at 9:00AM UTC, you will want the dataset for 6:00AM UTC. This will be explained a little further below.</p>
<div id="build-a-tracking-chart" class="section level2">
<h2 class="hasAnchor">
<a href="#build-a-tracking-chart" class="anchor"></a>Build a Tracking Chart</h2>
<p>There are three functions available to help you plot GIS data; <code>tracking_chart</code>, <code>al_tracking_chart</code> and <code>ep_tracking_chart</code>. <code>al_tracking_chart</code> and <code>ep_tracking_chart</code> are just helpers centered on the Atlantic and northeast Pacific ocean, respectively.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/args">args</a></span>(rrricanes<span class="op">::</span>tracking_chart)</a></code></pre></div>
<pre><code>## function (countries = TRUE, states = TRUE, res = 110, ...) 
## NULL</code></pre>
<p>The <code>countries</code> and <code>states</code> parameters are TRUE by default. This means a basic call to <code>tracking_chart</code> will return a map with country and state borders. The <code>res</code> parameter is resolution; one of 110, 50 or 10 nautical miles. Resolutions 110nm and 50nm can be used immediately. To use lower resolution you must install the <code>rnaturalearthdatahires</code> package from ropensci:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/install.packages">install.packages</a></span>(<span class="st">"rnaturalearthhires"</span>,</a>
<a class="sourceLine" id="cb4-2" data-line-number="2">                 <span class="dt">repos =</span> <span class="st">"http://packages.ropensci.org"</span>,</a>
<a class="sourceLine" id="cb4-3" data-line-number="3">                 <span class="dt">type =</span> <span class="st">"source"</span>)</a></code></pre></div>
<p><code>tracking_chart</code> will print a basic tracking chart (a map of the planet).</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw"><a href="../reference/tracking_chart.html">tracking_chart</a></span>()</a></code></pre></div>
<pre><code>## Regions defined for each Polygons
## Regions defined for each Polygons</code></pre>
<p><img src="gis_data_files/figure-html/unnamed-chunk-4-1.png" width="672" style="display: block; margin: auto;"></p>
<p>You can pass typical <code>aes</code> parameters to refine the color and fill of the plot; remember the tracking chart is a ggplot object.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw"><a href="../reference/tracking_chart.html">tracking_chart</a></span>(<span class="dt">color =</span> <span class="st">"black"</span>, <span class="dt">fill =</span> <span class="st">"white"</span>, <span class="dt">size =</span> <span class="fl">0.1</span>)</a></code></pre></div>
<pre><code>## Regions defined for each Polygons
## Regions defined for each Polygons</code></pre>
<p><img src="gis_data_files/figure-html/unnamed-chunk-5-1.png" width="672" style="display: block; margin: auto;"></p>
<p>You may choose to only show coastline data instead. In this case, just set the countries parameter to FALSE.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw"><a href="../reference/tracking_chart.html">tracking_chart</a></span>(<span class="dt">countries =</span> <span class="ot">FALSE</span>, <span class="dt">res =</span> <span class="dv">50</span>, <span class="dt">color =</span> <span class="st">"black"</span>, <span class="dt">fill =</span> <span class="st">"white"</span>, </a>
<a class="sourceLine" id="cb9-2" data-line-number="2">               <span class="dt">size =</span> <span class="fl">0.1</span>)</a></code></pre></div>
<p><img src="gis_data_files/figure-html/unnamed-chunk-6-1.png" width="672" style="display: block; margin: auto;"></p>
<p>For the purposes of this vignette we’ll focus on Atlantic storms.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" data-line-number="1">(p &lt;-<span class="st"> </span><span class="kw"><a href="../reference/al_tracking_chart.html">al_tracking_chart</a></span>(<span class="dt">color =</span> <span class="st">"black"</span>, <span class="dt">fill =</span> <span class="st">"white"</span>, <span class="dt">size =</span> <span class="fl">0.1</span>, <span class="dt">res =</span> <span class="dv">50</span>))</a></code></pre></div>
<pre><code>## Regions defined for each Polygons
## Regions defined for each Polygons</code></pre>
<pre><code>## Coordinate system already present. Adding new coordinate system, which will replace the existing one.</code></pre>
<p><img src="gis_data_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;"></p>
<p>The <code>res</code> parameter defines the resolution of the chart presented. Options are in 110nm, 50nm and 10nm. The lower the resolution the longer the chart takes to be built.</p>
<p>States cannot be drawn on resolution greater than 50nm.</p>
</div>
<div id="gis-datasets" class="section level2">
<h2 class="hasAnchor">
<a href="#gis-datasets" class="anchor"></a>GIS Datasets</h2>
<p>There are several datasets that are published for active cyclones. The following functions are designed to return the URL to those datasets:</p>
<ul>
<li><code>gis_advisory</code></li>
<li><code>gis_prob_storm_surge</code></li>
<li><code>gis_windfield</code></li>
<li><code>gis_latest</code></li>
</ul>
</div>
<div id="advisory-package" class="section level2">
<h2 class="hasAnchor">
<a href="#advisory-package" class="anchor"></a>Advisory Package</h2>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw"><a href="../reference/gis_advisory.html">gis_advisory</a></span>(<span class="dt">key =</span> <span class="st">"AL182012"</span>, <span class="dt">advisory =</span> <span class="st">"18"</span>)</a></code></pre></div>
<pre><code>## [1] "https://www.nhc.noaa.gov/gis/forecast/archive/al182012_5day_018.zip"</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1">df.gis_adv &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gis_advisory.html">gis_advisory</a></span>(<span class="dt">key =</span> <span class="st">"AL182012"</span>, <span class="dt">advisory =</span> <span class="st">"18"</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="../reference/gis_download.html">gis_download</a></span>()</a></code></pre></div>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/names">names</a></span>(df.gis_adv)</a></code></pre></div>
<pre><code>## [1] "al182012.018_5day_lin" "al182012.018_5day_pgn" "al182012.018_5day_pts"
## [4] "al182012.018_ww_wwlin"</code></pre>
<p>For this particular storm and advisory, included are the base line, point and polygon datasets along with a dataset for watches and warnings. The objects returned are spatial dataframes contained within the list of dataframes, <code>df.gis_adv</code>.</p>
<div id="line-track" class="section level3">
<h3 class="hasAnchor">
<a href="#line-track" class="anchor"></a>Line track</h3>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(df.gis_adv<span class="op">$</span>al182012<span class="fl">.018</span>_5day_lin)</a></code></pre></div>
<pre><code>## Formal class 'SpatialLinesDataFrame' [package "sp"] with 4 slots
##   ..@ data       :'data.frame':  2 obs. of  7 variables:
##   .. ..$ STORMNAME: chr [1:2] "SANDY" "SANDY"
##   .. ..$ STORMTYPE: chr [1:2] "HU" "HU"
##   .. ..$ ADVDATE  : chr [1:2] "121026/2100" "121026/2100"
##   .. ..$ ADVISNUM : chr [1:2] "18" "18"
##   .. ..$ STORMNUM : num [1:2] 18 18
##   .. ..$ FCSTPRD  : num [1:2] 72 120
##   .. ..$ BASIN    : chr [1:2] "al" "al"
##   ..@ lines      :List of 2
##   .. ..$ :Formal class 'Lines' [package "sp"] with 2 slots
##   .. .. .. ..@ Lines:List of 1
##   .. .. .. .. ..$ :Formal class 'Line' [package "sp"] with 1 slot
##   .. .. .. .. .. .. ..@ coords: num [1:6, 1:2] -77.1 -77 -76.1 -74.3 -72.6 ...
##   .. .. .. ..@ ID   : chr "0"
##   .. ..$ :Formal class 'Lines' [package "sp"] with 2 slots
##   .. .. .. ..@ Lines:List of 1
##   .. .. .. .. ..$ :Formal class 'Line' [package "sp"] with 1 slot
##   .. .. .. .. .. .. ..@ coords: num [1:8, 1:2] -77.1 -77 -76.1 -74.3 -72.6 ...
##   .. .. .. ..@ ID   : chr "1"
##   ..@ bbox       : num [1:2, 1:2] -77.1 27.3 -71.5 41
##   .. ..- attr(*, "dimnames")=List of 2
##   .. .. ..$ : chr [1:2] "x" "y"
##   .. .. ..$ : chr [1:2] "min" "max"
##   ..@ proj4string:Formal class 'CRS' [package "sp"] with 1 slot
##   .. .. ..@ projargs: chr "+proj=longlat +a=6371200 +b=6371200 +no_defs"</code></pre>
<p>As we’re dealing with a SpatialLinesDataFrame which needs to be modified, you can use the helper function <code>shp_to_df</code> for plotting.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1">fcst_line &lt;-<span class="st"> </span><span class="kw"><a href="../reference/shp_to_df.html">shp_to_df</a></span>(df.gis_adv<span class="op">$</span>al182012<span class="fl">.018</span>_5day_lin)</a></code></pre></div>
<pre><code>## Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character</code></pre>
<pre><code>## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1">p <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_path</a></span>(<span class="dt">data =</span> fcst_line, <span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(long, lat, <span class="dt">group =</span> FCSTPRD))</a></code></pre></div>
<p><img src="gis_data_files/figure-html/unnamed-chunk-13-1.png" width="672" style="display: block; margin: auto;"></p>
<p>There are two groups of data in the set: one for 72-hour forecast period and one for 120-hour. Grouping by <code>FCSTPRD</code> will show the forecast track correctly.</p>
<p>There is a pretty wide field of view on the map above. You can use <code><a href="https://www.rdocumentation.org/packages/sp/topics/bbox">sp::bbox</a></code> to “zoom in” on the map.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1">(bb &lt;-<span class="st"> </span>sp<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/bbox">bbox</a></span>(df.gis_adv<span class="op">$</span>al182012<span class="fl">.018</span>_5day_lin))</a></code></pre></div>
<pre><code>##     min   max
## x -77.1 -71.5
## y  27.3  41.0</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" data-line-number="1">(p2 &lt;-<span class="st"> </span>p <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_path</a></span>(<span class="dt">data =</span> fcst_line, <span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(long, lat, <span class="dt">group =</span> FCSTPRD)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb26-2" data-line-number="2"><span class="st">    </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/coord_fixed">coord_equal</a></span>(<span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bb[<span class="dv">1</span>,<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span><span class="dv">5</span>, bb[<span class="dv">1</span>,<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span><span class="dv">5</span>), </a>
<a class="sourceLine" id="cb26-3" data-line-number="3">                <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bb[<span class="dv">2</span>,<span class="dv">1</span>] <span class="op">-</span><span class="st"> </span><span class="dv">5</span>, bb[<span class="dv">2</span>,<span class="dv">2</span>] <span class="op">+</span><span class="st"> </span><span class="dv">5</span>)))</a></code></pre></div>
<pre><code>## Coordinate system already present. Adding new coordinate system, which will replace the existing one.</code></pre>
<p><img src="gis_data_files/figure-html/unnamed-chunk-15-1.png" width="672" style="display: block; margin: auto;"></p>
</div>
<div id="point-track" class="section level3">
<h3 class="hasAnchor">
<a href="#point-track" class="anchor"></a>Point track</h3>
<p>Each forecast position is also included in the points dataframe. You can access this in the <code>df.gis_adv$al182012.018_5day_pts@data</code> object; no conversion necessary.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" data-line-number="1">(p3 &lt;-<span class="st"> </span>p2 <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/geom_point">geom_point</a></span>(<span class="dt">data =</span> df.gis_adv<span class="op">$</span>al182012<span class="fl">.018</span>_5day_pts<span class="op">@</span>data, <span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(LON, LAT)))</a></code></pre></div>
<p><img src="gis_data_files/figure-html/unnamed-chunk-16-1.png" width="672" style="display: block; margin: auto;"></p>
</div>
</div>
<div id="forecast-cone" class="section level2">
<h2 class="hasAnchor">
<a href="#forecast-cone" class="anchor"></a>Forecast Cone</h2>
<p>Forecast cone data is contained in the polygon dataset. To deal with this dataset you can use the <code>shp_to_df</code> function again or take the slightly longer way:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1">fcst_cone &lt;-<span class="st"> </span>df.gis_adv<span class="op">$</span>al182012<span class="fl">.018</span>_5day_pgn</a>
<a class="sourceLine" id="cb29-2" data-line-number="2">fcst_cone<span class="op">@</span>data<span class="op">$</span>id &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/colnames">rownames</a></span>(fcst_cone<span class="op">@</span>data)</a>
<a class="sourceLine" id="cb29-3" data-line-number="3">fcst_cone.points &lt;-<span class="st"> </span>broom<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/broom/topics/reexports">tidy</a></span>(fcst_cone, <span class="dt">region =</span> <span class="st">"id"</span>)</a></code></pre></div>
<pre><code>## Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character</code></pre>
<pre><code>## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" data-line-number="1">fcst_cone &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw"><a href="https://dplyr.tidyverse.org/reference/join.html">left_join</a></span>(fcst_cone.points, fcst_cone<span class="op">@</span>data, <span class="dt">by =</span> <span class="st">"id"</span>)</a></code></pre></div>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1">p3 <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/geom_polygon">geom_polygon</a></span>(<span class="dt">data =</span> fcst_cone <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span>(FCSTPRD <span class="op">==</span><span class="st"> </span><span class="dv">120</span>), </a>
<a class="sourceLine" id="cb33-2" data-line-number="2">                 <span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(long, lat, <span class="dt">group =</span> group, <span class="dt">fill =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(FCSTPRD)), </a>
<a class="sourceLine" id="cb33-3" data-line-number="3">                 <span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb33-4" data-line-number="4"><span class="st">    </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/geom_polygon">geom_polygon</a></span>(<span class="dt">data =</span> fcst_cone <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span>(FCSTPRD <span class="op">==</span><span class="st"> </span><span class="dv">72</span>), </a>
<a class="sourceLine" id="cb33-5" data-line-number="5">                 <span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(long, lat, <span class="dt">group =</span> group, <span class="dt">fill =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(FCSTPRD)), </a>
<a class="sourceLine" id="cb33-6" data-line-number="6">                 <span class="dt">alpha =</span> <span class="fl">0.5</span>)</a></code></pre></div>
<p><img src="gis_data_files/figure-html/unnamed-chunk-18-1.png" width="672" style="display: block; margin: auto;"></p>
<p>Note that in some GIS packages the forecast cones may be identical (though they shouldn’t be). I’ve noticed it with Hurricanes Ike and Matthew; it’s in the raw dataset.</p>
</div>
<div id="watches-and-warnings" class="section level2">
<h2 class="hasAnchor">
<a href="#watches-and-warnings" class="anchor"></a>Watches and Warnings</h2>
<p>You can also plot watches and warnings if any are in effect for the package release time.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" data-line-number="1">ww_line &lt;-<span class="st"> </span><span class="kw"><a href="../reference/shp_to_df.html">shp_to_df</a></span>(df.gis_adv<span class="op">$</span>al182012<span class="fl">.018</span>_ww_wwlin)</a></code></pre></div>
<pre><code>## Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character</code></pre>
<pre><code>## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1">p3 <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_path</a></span>(<span class="dt">data =</span> ww_line, </a>
<a class="sourceLine" id="cb37-2" data-line-number="2">               <span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group, <span class="dt">color =</span> TCWW), <span class="dt">size =</span> <span class="dv">1</span>)</a></code></pre></div>
<p><img src="gis_data_files/figure-html/unnamed-chunk-20-1.png" width="672" style="display: block; margin: auto;"></p>
<p>In the example above you can see tropical storm warnings issued for the Bahamas, North Carolina and portions of the South Carolina and Florida coast while tropical storm watches are in effect for northern Florida and South Carolina.</p>
</div>
<div id="probabilistic-storm-surge" class="section level2">
<h2 class="hasAnchor">
<a href="#probabilistic-storm-surge" class="anchor"></a>Probabilistic Storm Surge</h2>
<p>The Tropical Cyclone Storm Surge Probabilities data shows the probability, in percent, of a specified storm surge occurring during the forecast period indicated. The product is based upon an ensemble of Sea, Lake, and Overland Surge from Hurricanes (SLOSH) model runs using the National Hurricane Center (NHC) official advisory and accounts for track, size, and intensity errors based on historical errors.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1"><span class="kw"><a href="../reference/gis_prob_storm_surge.html">gis_prob_storm_surge</a></span>(<span class="dt">key =</span> <span class="st">"AL142016"</span>, <span class="dt">products =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">psurge =</span> <span class="dv">0</span>), </a>
<a class="sourceLine" id="cb38-2" data-line-number="2">                     <span class="dt">datetime =</span> <span class="st">"20161006"</span>)</a></code></pre></div>
<pre><code>## [1] "https://www.nhc.noaa.gov/gis/storm_surge/al142016_psurge0_2016100600.zip"
## [2] "https://www.nhc.noaa.gov/gis/storm_surge/al142016_psurge0_2016100606.zip"
## [3] "https://www.nhc.noaa.gov/gis/storm_surge/al142016_psurge0_2016100612.zip"
## [4] "https://www.nhc.noaa.gov/gis/storm_surge/al142016_psurge0_2016100618.zip"</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1">df.gis_storm_surge &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gis_prob_storm_surge.html">gis_prob_storm_surge</a></span>(<span class="dt">key =</span> <span class="st">"AL142016"</span>, </a>
<a class="sourceLine" id="cb40-2" data-line-number="2">                           <span class="dt">products =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">psurge =</span> <span class="dv">0</span>), </a>
<a class="sourceLine" id="cb40-3" data-line-number="3">                           <span class="dt">datetime =</span> <span class="st">"20161006"</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb40-4" data-line-number="4"><span class="st">    </span><span class="kw"><a href="https://dplyr.tidyverse.org/reference/nth.html">last</a></span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb40-5" data-line-number="5"><span class="st">    </span><span class="kw"><a href="../reference/gis_download.html">gis_download</a></span>()</a></code></pre></div>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1">prob_surge &lt;-<span class="st"> </span><span class="kw"><a href="../reference/shp_to_df.html">shp_to_df</a></span>(df.gis_storm_surge<span class="op">$</span>al142016_<span class="dv">2016100618</span>_gt0)</a></code></pre></div>
<pre><code>## Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character</code></pre>
<pre><code>## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector</code></pre>
<pre><code>## Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character</code></pre>
<pre><code>## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1">bb &lt;-<span class="st"> </span>sp<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/bbox">bbox</a></span>(df.gis_storm_surge<span class="op">$</span>al142016_<span class="dv">2016100618</span>_gt0)</a></code></pre></div>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1">p <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/geom_path">geom_path</a></span>(<span class="dt">data =</span> prob_surge, </a>
<a class="sourceLine" id="cb47-2" data-line-number="2">               <span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group, <span class="dt">color =</span> PSurge00c), </a>
<a class="sourceLine" id="cb47-3" data-line-number="3">              <span class="dt">size =</span> <span class="dv">1</span>, <span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb47-4" data-line-number="4"><span class="st">    </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/coord_fixed">coord_equal</a></span>(<span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bb[<span class="dv">1</span>,<span class="dv">1</span>], bb[<span class="dv">1</span>,<span class="dv">2</span>]), <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bb[<span class="dv">2</span>,<span class="dv">1</span>], bb[<span class="dv">2</span>,<span class="dv">2</span>]))</a></code></pre></div>
<pre><code>## Coordinate system already present. Adding new coordinate system, which will replace the existing one.</code></pre>
<p><img src="gis_data_files/figure-html/unnamed-chunk-24-1.png" width="672" style="display: block; margin: auto;"></p>
</div>
<div id="current-and-forecast-wind-field-radii" class="section level2">
<h2 class="hasAnchor">
<a href="#current-and-forecast-wind-field-radii" class="anchor"></a>Current and Forecast Wind Field Radii</h2>
<p>Wind radii data may also be available for some cyclone advisory packages. This is the radius to which a minimum sustained wind speed may be felt from the center of circulation.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" data-line-number="1"><span class="kw"><a href="../reference/gis_windfield.html">gis_windfield</a></span>(<span class="st">"AL142016"</span>, <span class="dt">advisory =</span> <span class="st">"33"</span>)</a></code></pre></div>
<pre><code>## [1] "https://www.nhc.noaa.gov/gis/forecast/archive/al142016_fcst_033.zip"</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" data-line-number="1">df.gis_wind_radii &lt;-<span class="st"> </span><span class="kw"><a href="../reference/gis_windfield.html">gis_windfield</a></span>(<span class="st">"AL142016"</span>, <span class="dt">advisory =</span> <span class="st">"33"</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw"><a href="../reference/gis_download.html">gis_download</a></span>()</a></code></pre></div>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" data-line-number="1">wf_init &lt;-<span class="st"> </span><span class="kw"><a href="../reference/shp_to_df.html">shp_to_df</a></span>(df.gis_wind_radii<span class="op">$</span>al142016_<span class="dv">2016100606</span>_initialradii)</a></code></pre></div>
<pre><code>## Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character</code></pre>
<pre><code>## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" data-line-number="1">bb &lt;-<span class="st"> </span>sp<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/bbox">bbox</a></span>(df.gis_wind_radii<span class="op">$</span>al142016_<span class="dv">2016100606</span>_forecastradii)</a></code></pre></div>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" data-line-number="1">(p4 &lt;-<span class="st"> </span>p <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/geom_polygon">geom_polygon</a></span>(<span class="dt">data =</span> wf_init, </a>
<a class="sourceLine" id="cb56-2" data-line-number="2">                  <span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">fill =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(RADII)), <span class="dt">alpha =</span> <span class="fl">0.5</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb56-3" data-line-number="3"><span class="st">    </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/coord_fixed">coord_equal</a></span>(<span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bb[<span class="dv">1</span>,<span class="dv">1</span>], bb[<span class="dv">1</span>,<span class="dv">2</span>]), <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bb[<span class="dv">2</span>,<span class="dv">1</span>], bb[<span class="dv">2</span>,<span class="dv">2</span>])))</a></code></pre></div>
<pre><code>## Coordinate system already present. Adding new coordinate system, which will replace the existing one.</code></pre>
<p><img src="gis_data_files/figure-html/unnamed-chunk-28-1.png" width="672" style="display: block; margin: auto;"></p>
<p>Additionally, forecast wind radii data is also generally available in some packages</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1">wf_fcst &lt;-<span class="st"> </span><span class="kw"><a href="../reference/shp_to_df.html">shp_to_df</a></span>(df.gis_wind_radii<span class="op">$</span>al142016_<span class="dv">2016100606</span>_forecastradii)</a></code></pre></div>
<pre><code>## Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character</code></pre>
<pre><code>## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector

## Warning in bind_rows_(x, .id): binding character and factor vector,
## coercing into character vector</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" data-line-number="1">p4 <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/geom_polygon">geom_polygon</a></span>(<span class="dt">data =</span> wf_fcst, </a>
<a class="sourceLine" id="cb61-2" data-line-number="2">                  <span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group, <span class="dt">fill =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(RADII)), </a>
<a class="sourceLine" id="cb61-3" data-line-number="3">                  <span class="dt">alpha =</span> <span class="fl">0.5</span>)</a></code></pre></div>
<p><img src="gis_data_files/figure-html/unnamed-chunk-30-1.png" width="672" style="display: block; margin: auto;"></p>
</div>
<div id="wind-speed-probabilities" class="section level2">
<h2 class="hasAnchor">
<a href="#wind-speed-probabilities" class="anchor"></a>Wind Speed Probabilities</h2>
<p>Wind Speed probabilities show the chance of experiencing a minimum-sustained winds of 34, 50 and 64 knots with a given period of time (typically, 120 hours). These products are not storm-specific but are global so other active cyclones in other basins may also appear.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" data-line-number="1"><span class="kw"><a href="../reference/gis_wsp.html">gis_wsp</a></span>(<span class="dt">datetime =</span> <span class="st">"2016100606"</span>, <span class="dt">res =</span> <span class="fl">0.5</span>)</a></code></pre></div>
<pre><code>## [1] "https://www.nhc.noaa.gov/gis/forecast/archive/2016100606_wsp_120hrhalfDeg.zip"</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1">df.gis_wsp &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb64-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/gis_download.html">gis_download</a></span>(</a>
<a class="sourceLine" id="cb64-3" data-line-number="3">    <span class="st">"https://www.nhc.noaa.gov/gis/forecast/archive/2016100606_wsp_120hrhalfDeg.zip"</span></a>
<a class="sourceLine" id="cb64-4" data-line-number="4">  )</a></code></pre></div>
<div id="cumulative-probability-for-34kt-winds" class="section level3">
<h3 class="hasAnchor">
<a href="#cumulative-probability-for-34kt-winds" class="anchor"></a>Cumulative Probability for &gt;34kt Winds</h3>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" data-line-number="1">bb &lt;-<span class="st"> </span>sp<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/bbox">bbox</a></span>(df.gis_wsp<span class="op">$</span><span class="st">`</span><span class="dt">2016100606_wsp34knt120hr_halfDeg</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb65-2" data-line-number="2">p <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb65-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/ggsf">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb65-4" data-line-number="4">    <span class="dt">data =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/sf/topics/st_as_sf">st_as_sf</a></span>(df.gis_wsp<span class="op">$</span><span class="st">`</span><span class="dt">2016100606_wsp34knt120hr_halfDeg</span><span class="st">`</span>), </a>
<a class="sourceLine" id="cb65-5" data-line-number="5">    <span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">color =</span> PWIND120)</a>
<a class="sourceLine" id="cb65-6" data-line-number="6">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb65-7" data-line-number="7"><span class="st">  </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/ggsf">coord_sf</a></span>(<span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bb[<span class="dv">1</span>,<span class="dv">1</span>], bb[<span class="dv">1</span>,<span class="dv">2</span>]), <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bb[<span class="dv">2</span>,<span class="dv">1</span>], bb[<span class="dv">2</span>,<span class="dv">2</span>]))</a></code></pre></div>
<pre><code>## Coordinate system already present. Adding new coordinate system, which will replace the existing one.</code></pre>
<p><img src="gis_data_files/figure-html/unnamed-chunk-33-1.png" width="672" style="display: block; margin: auto;"></p>
<p>Cumulative wind speed probability for &gt;50kt winds:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" data-line-number="1">bb &lt;-<span class="st"> </span>sp<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/bbox">bbox</a></span>(df.gis_wsp<span class="op">$</span><span class="st">`</span><span class="dt">2016100606_wsp50knt120hr_halfDeg</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb67-2" data-line-number="2">p <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb67-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/ggsf">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb67-4" data-line-number="4">    <span class="dt">data =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/sf/topics/st_as_sf">st_as_sf</a></span>(df.gis_wsp<span class="op">$</span><span class="st">`</span><span class="dt">2016100606_wsp50knt120hr_halfDeg</span><span class="st">`</span>), </a>
<a class="sourceLine" id="cb67-5" data-line-number="5">    <span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">color =</span> PWIND120)</a>
<a class="sourceLine" id="cb67-6" data-line-number="6">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb67-7" data-line-number="7"><span class="st">  </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/ggsf">coord_sf</a></span>(<span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bb[<span class="dv">1</span>,<span class="dv">1</span>], bb[<span class="dv">1</span>,<span class="dv">2</span>]), <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bb[<span class="dv">2</span>,<span class="dv">1</span>], bb[<span class="dv">2</span>,<span class="dv">2</span>]))</a></code></pre></div>
<pre><code>## Coordinate system already present. Adding new coordinate system, which will replace the existing one.</code></pre>
<p><img src="gis_data_files/figure-html/unnamed-chunk-34-1.png" width="672" style="display: block; margin: auto;"></p>
<p>Cumulative probability for &gt;64kt winds:</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" data-line-number="1">bb &lt;-<span class="st"> </span>sp<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sp/topics/bbox">bbox</a></span>(df.gis_wsp<span class="op">$</span><span class="st">`</span><span class="dt">2016100606_wsp64knt120hr_halfDeg</span><span class="st">`</span>)</a>
<a class="sourceLine" id="cb69-2" data-line-number="2">p <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb69-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/ggsf">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb69-4" data-line-number="4">    <span class="dt">data =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/sf/topics/st_as_sf">st_as_sf</a></span>(df.gis_wsp<span class="op">$</span><span class="st">`</span><span class="dt">2016100606_wsp64knt120hr_halfDeg</span><span class="st">`</span>), </a>
<a class="sourceLine" id="cb69-5" data-line-number="5">    <span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/aes">aes</a></span>(<span class="dt">color =</span> PWIND120)</a>
<a class="sourceLine" id="cb69-6" data-line-number="6">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb69-7" data-line-number="7"><span class="st">  </span><span class="kw"><a href="https://www.rdocumentation.org/packages/ggplot2/topics/ggsf">coord_sf</a></span>(<span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bb[<span class="dv">1</span>,<span class="dv">1</span>], bb[<span class="dv">1</span>,<span class="dv">2</span>]), <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bb[<span class="dv">2</span>,<span class="dv">1</span>], bb[<span class="dv">2</span>,<span class="dv">2</span>]))</a></code></pre></div>
<pre><code>## Coordinate system already present. Adding new coordinate system, which will replace the existing one.</code></pre>
<p><img src="gis_data_files/figure-html/unnamed-chunk-35-1.png" width="672" style="display: block; margin: auto;"></p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#build-a-tracking-chart">Build a Tracking Chart</a></li>
      <li><a href="#gis-datasets">GIS Datasets</a></li>
      <li><a href="#advisory-package">Advisory Package</a></li>
      <li><a href="#forecast-cone">Forecast Cone</a></li>
      <li><a href="#watches-and-warnings">Watches and Warnings</a></li>
      <li><a href="#probabilistic-storm-surge">Probabilistic Storm Surge</a></li>
      <li><a href="#current-and-forecast-wind-field-radii">Current and Forecast Wind Field Radii</a></li>
      <li><a href="#wind-speed-probabilities">Wind Speed Probabilities</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Tim Trice.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
