<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Retrieving and Plotting GIS Data • rrricanes</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><!-- docsearch --><script src="../docsearch.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.css" integrity="sha256-QOSRU/ra9ActyXkIBbiIB144aDBdtvXBcNc3OTNuX/Q=" crossorigin="anonymous">
<link href="../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script><meta property="og:title" content="Retrieving and Plotting GIS Data">
<meta property="og:description" content="">
<meta property="og:image" content="https://ropensci.github.io/rrricanes/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]--><!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=UA-1507390-27"></script><script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-1507390-27');
</script>
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">rrricanes</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.2.0.6.9002</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/getting_started.html">Getting Started</a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Tutorials
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/accumulated_cyclone_energy.html">Accumulated Cyclone Energy</a>
    </li>
    <li>
      <a href="../articles/gis_data.html">GIS Data</a>
    </li>
    <li>
      <a href="../articles/wind_pressure.html">Wind and Pressure</a>
    </li>
    <li>
      <a href="../articles/installing_rrricanesdata.html">rrricanesdata</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/ropensci/rrricanes">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
<form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
      </form>
      
    </div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Retrieving and Plotting GIS Data</h1>
                        <h4 class="author">Tim Trice</h4>
            
            <h4 class="date">2019-07-03</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/ropensci/rrricanes/blob/master/vignettes/gis_data.Rmd"><code>vignettes/gis_data.Rmd</code></a></small>
      <div class="hidden name"><code>gis_data.Rmd</code></div>

    </div>

    
    
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(dplyr)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(rrricanes)</a>
<a class="sourceLine" id="cb1-4" data-line-number="4"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(sf)</a></code></pre></div>
<p>Most storms will contain a variation of GIS datasets that can be plotted with <code>ggplot2</code>. The helper functions for this have the prefix ‘gis’.</p>
<p><strong>All products are experimental and there maybe fluctuations particularly in current datasets.</strong></p>
<p>In general, datasets are available for storms dated back to 1998. However, products such as Wind Speed Probabilities only go back to 1999.</p>
<p>Some datasets require the use of the storm key and an optional advisory. Other products require a datetime value and cannot be isolated by storm key or advisory. The datetime values are not based on the issue time of the advisory, but rather three hours prior. For example, if you are seeking a dataset where the forecast/advisory was issued at 9:00AM UTC, you will want the dataset for 6:00AM UTC. This will be explained a little further below.</p>
<div id="build-a-tracking-chart" class="section level2">
<h2 class="hasAnchor">
<a href="#build-a-tracking-chart" class="anchor"></a>Build a Tracking Chart</h2>
<p>As of version 0.2.7, the built-in tracking chart functions have been removed. Users are encouraged to use the <code>rnaturalearthdata</code> and associated packages to build tracking charts.</p>
<p>The <code>rnaturalearthdata</code> package has many shapefile datasets that can be used to make maps. For this article I will only need countries and states. I will use the resolution of 10 nautical miles (available in the <code>rnaturalearthhires</code> package). Each dataset is named <code>countries10</code> and <code>states10</code>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1">p &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb2-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb2-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb2-4" data-line-number="4">    <span class="dt">data =</span> sf<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sf/topics/st_as_sf">st_as_sf</a></span>(rnaturalearthhires<span class="op">::</span>countries10), </a>
<a class="sourceLine" id="cb2-5" data-line-number="5">    <span class="dt">fill =</span> <span class="st">"gray95"</span>, </a>
<a class="sourceLine" id="cb2-6" data-line-number="6">    <span class="dt">color =</span> <span class="st">"black"</span>, </a>
<a class="sourceLine" id="cb2-7" data-line-number="7">    <span class="dt">size =</span> <span class="fl">0.1</span></a>
<a class="sourceLine" id="cb2-8" data-line-number="8">  )  <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb2-9" data-line-number="9"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb2-10" data-line-number="10">    <span class="dt">data =</span> sf<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sf/topics/st_as_sf">st_as_sf</a></span>(rnaturalearthhires<span class="op">::</span>states10), </a>
<a class="sourceLine" id="cb2-11" data-line-number="11">    <span class="dt">fill =</span> <span class="st">"gray95"</span>,</a>
<a class="sourceLine" id="cb2-12" data-line-number="12">    <span class="dt">size =</span> <span class="fl">0.1</span></a>
<a class="sourceLine" id="cb2-13" data-line-number="13">  )</a>
<a class="sourceLine" id="cb2-14" data-line-number="14">p</a></code></pre></div>
<p><img src="gis_data_files/figure-html/base-plot-1.png" width="672" style="display: block; margin: auto;"></p>
<p>I’ll also remove the padding around the plot and change the color of the seas (<code>panel.background</code>).</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1">p &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb3-2" data-line-number="2"><span class="st">  </span>p <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb3-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_x_continuous</a></span>(</a>
<a class="sourceLine" id="cb3-4" data-line-number="4">    <span class="dt">expand =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">0</span>, <span class="dv">0</span>)</a>
<a class="sourceLine" id="cb3-5" data-line-number="5">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb3-6" data-line-number="6"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span>(</a>
<a class="sourceLine" id="cb3-7" data-line-number="7">    <span class="dt">expand =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">0</span>, <span class="dv">0</span>)</a>
<a class="sourceLine" id="cb3-8" data-line-number="8">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb3-9" data-line-number="9"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(</a>
<a class="sourceLine" id="cb3-10" data-line-number="10">    <span class="dt">panel.background =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_rect</a></span>(<span class="dt">fill =</span> <span class="st">"white"</span>),</a>
<a class="sourceLine" id="cb3-11" data-line-number="11">    <span class="dt">panel.grid.major =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_line</a></span>(<span class="dt">color =</span> <span class="st">"black"</span>, <span class="dt">size =</span> <span class="fl">0.1</span>)</a>
<a class="sourceLine" id="cb3-12" data-line-number="12">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb3-13" data-line-number="13"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span>(</a>
<a class="sourceLine" id="cb3-14" data-line-number="14">    <span class="dt">x =</span> <span class="st">""</span>, </a>
<a class="sourceLine" id="cb3-15" data-line-number="15">    <span class="dt">y =</span> <span class="st">""</span>, </a>
<a class="sourceLine" id="cb3-16" data-line-number="16">    <span class="dt">caption =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sprintf">sprintf</a></span>(<span class="st">"rrricanes %s"</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/packageDescription">packageVersion</a></span>(<span class="st">"rrricanes"</span>))</a>
<a class="sourceLine" id="cb3-17" data-line-number="17">  )</a>
<a class="sourceLine" id="cb3-18" data-line-number="18">p</a></code></pre></div>
<p><img src="gis_data_files/figure-html/base-plot-plus-scale-1.png" width="672" style="display: block; margin: auto;"></p>
</div>
<div id="gis-datasets" class="section level2">
<h2 class="hasAnchor">
<a href="#gis-datasets" class="anchor"></a>GIS Datasets</h2>
<p>There are several datasets that are published for active cyclones. The following functions are designed to return the URL to those datasets:</p>
<ul>
<li><code>gis_advisory</code></li>
<li><code>gis_prob_storm_surge</code></li>
<li><code>gis_windfield</code></li>
<li>
<code>gis_latest</code> (only for active storms)</li>
</ul>
<p>It’s important to note that not every storm will have a dataset available. Nor are datasets consistent from one storm to the next. For example, as we’ll see below, a forecast cone should have two polygons for a 72-hour and 120-hour forecast; in this example, they are both 120-hours.</p>
<p>Let’s take a look at Hurricane Matthew (AL142016) and focus on advisory 37.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" data-line-number="1">key &lt;-<span class="st"> "AL142016"</span></a>
<a class="sourceLine" id="cb4-2" data-line-number="2">adv &lt;-<span class="st"> </span><span class="dv">37</span></a></code></pre></div>
<div id="data-scraping" class="section level3">
<h3 class="hasAnchor">
<a href="#data-scraping" class="anchor"></a>Data Scraping</h3>
<p>The functions listed above do not retrieve the data. They only return the URLs. This is to give you the opportunity to modify your requests to get the specific data needed, if it exists.</p>
<div id="gis_advisory" class="section level4">
<h4 class="hasAnchor">
<a href="#gis_advisory" class="anchor"></a><code>gis_advisory</code>
</h4>
<p>The <code>gis_advisory</code> function returns the URL for the GIS dataset by <code>key</code> and <code>advisory</code> number. Remember, a storm’s key should always be eight alphanumeric characters;</p>
<ul>
<li><p>Basin identifier (“AL”, “CP”, or “EP”)</p></li>
<li><p>Storm number for the year</p></li>
<li><p>The four digit year</p></li>
</ul>
<p>The <code>fstadv</code> product will always have the storm key. In earlier years, the “year” portion of the key was only the year without the century; you will need to add it.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/args">args</a></span>(gis_advisory)</a></code></pre></div>
<pre><code>## function (key, advisory = as.character()) 
## NULL</code></pre>
<p>We can test that an advisory package does exist for our specific advisory.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1"><span class="kw"><a href="../reference/gis_advisory.html">gis_advisory</a></span>(<span class="dt">key =</span> key, <span class="dt">advisory =</span> adv)</a></code></pre></div>
<pre><code>## [1] "https://www.nhc.noaa.gov/gis/forecast/archive/al142016_5day_037.zip"</code></pre>
<p>This should work.</p>
</div>
<div id="gis_windfield" class="section level4">
<h4 class="hasAnchor">
<a href="#gis_windfield" class="anchor"></a><code>gis_windfield</code>
</h4>
<p>The <code>gis_windfield</code> product is relatively new so it may not exist for some storms. As with <code>gis_advisory</code>, we only need the storms’ key and advisory.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/args">args</a></span>(gis_windfield)</a></code></pre></div>
<pre><code>## function (key, advisory = as.character()) 
## NULL</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1"><span class="kw"><a href="../reference/gis_windfield.html">gis_windfield</a></span>(<span class="dt">key =</span> key, <span class="dt">advisory =</span> adv)</a></code></pre></div>
<pre><code>## [1] "https://www.nhc.noaa.gov/gis/forecast/archive/al142016_fcst_037.zip"</code></pre>
</div>
<div id="gis_prob_storm_surge" class="section level4">
<h4 class="hasAnchor">
<a href="#gis_prob_storm_surge" class="anchor"></a><code>gis_prob_storm_surge</code>
</h4>
<p>The function <code>gis_prob_storm_surge</code> also uses the <code>key</code> variable, but not the advisory; instead, it uses <code>datetime</code>.</p>
<p>There are two types of products that can be retrieved, “esurge” and “psurge”. psurge shows the probability of a specific height (in feet) of storm surge affecting an area. Values between 0 and 20 can be used.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1"><span class="kw"><a href="../reference/gis_prob_storm_surge.html">gis_prob_storm_surge</a></span>(</a>
<a class="sourceLine" id="cb13-2" data-line-number="2">  <span class="dt">key =</span> key, </a>
<a class="sourceLine" id="cb13-3" data-line-number="3">  <span class="dt">datetime =</span> <span class="st">"2016100706"</span>, </a>
<a class="sourceLine" id="cb13-4" data-line-number="4">  <span class="dt">products =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(</a>
<a class="sourceLine" id="cb13-5" data-line-number="5">    <span class="co"># esurge = 10</span></a>
<a class="sourceLine" id="cb13-6" data-line-number="6">    <span class="dt">psurge =</span> <span class="dv">5</span></a>
<a class="sourceLine" id="cb13-7" data-line-number="7">  )</a>
<a class="sourceLine" id="cb13-8" data-line-number="8">)</a></code></pre></div>
<p>In the example above, we are requesting the probabilities of a 5-foot storm surge affecting the coastline and inland waterways.</p>
<p>esurge shows the probability of a specific storm surge height exceeding the forecast height. Valid values are 10, 20, 30, 04, and 50. Note the commented section in the code above.</p>
<p>The <code>products</code> parameter expects a list, though you do not need to include both products. Additionally, each product expects a numeric or numeric vector. If you make a broad general request, the National Hurricane Center requests no more than 80 requests per 10 seconds, so please be respectful. Unlike retrieving text products, there is no throttle in this package to download GIS datasets.</p>
<p>Regarding <code>datetime</code>, this value should be that of the advisory time minus 3 hours not including minutes and seconds. Let’s get that value for Matthew’s #37 advisory.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" data-line-number="1">datetime &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb14-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="../reference/get_storms.html">get_storms</a></span>(<span class="dt">years =</span> <span class="st">"2016"</span>, <span class="dt">basins =</span> <span class="st">"AL"</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb14-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span>(Name <span class="op">==</span><span class="st"> "Hurricane Matthew"</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb14-4" data-line-number="4"><span class="st">  </span><span class="kw"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span>(Link) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb14-5" data-line-number="5"><span class="st">  </span><span class="kw"><a href="../reference/get_fstadv.html">get_fstadv</a></span>() <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb14-6" data-line-number="6"><span class="st">  </span><span class="kw"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span>(Adv <span class="op">==</span><span class="st"> </span>adv) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb14-7" data-line-number="7"><span class="st">  </span><span class="kw"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span>(Date)</a></code></pre></div>
<pre><code>## Registered S3 method overwritten by 'httr':
##   method                 from
##   as.character.form_file crul</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" data-line-number="1"><span class="co"># Subtract 3 hours</span></a>
<a class="sourceLine" id="cb16-2" data-line-number="2">datetime &lt;-<span class="st"> </span>datetime <span class="op">-</span><span class="st"> </span><span class="dv">3</span> <span class="op">*</span><span class="st"> </span><span class="dv">60</span> <span class="op">*</span><span class="st"> </span><span class="dv">60</span></a>
<a class="sourceLine" id="cb16-3" data-line-number="3"></a>
<a class="sourceLine" id="cb16-4" data-line-number="4"><span class="co"># Turn into string without the seconds. Format is YYYYMMDDHH</span></a>
<a class="sourceLine" id="cb16-5" data-line-number="5">datetime &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.Date">as.character.Date</a></span>(datetime, <span class="st">"%Y%m%d%H"</span>)</a>
<a class="sourceLine" id="cb16-6" data-line-number="6"></a>
<a class="sourceLine" id="cb16-7" data-line-number="7">datetime</a></code></pre></div>
<pre><code>## [1] "2016100706"</code></pre>
<p>Let’s make sure we can get a psurge 5 product for this datetime value.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" data-line-number="1"><span class="kw"><a href="../reference/gis_prob_storm_surge.html">gis_prob_storm_surge</a></span>(<span class="dt">key =</span> key, <span class="dt">products =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">psurge =</span> <span class="dv">5</span>), <span class="dt">datetime =</span> datetime)</a></code></pre></div>
<pre><code>## [1] "https://www.nhc.noaa.gov/gis/storm_surge/al142016_psurge5_2016100706.zip"</code></pre>
<p>Looks good.</p>
<div id="gis_wsp" class="section level5">
<h5 class="hasAnchor">
<a href="#gis_wsp" class="anchor"></a><code>gis_wsp</code>
</h5>
<p>Wind speed probabilities exist in the <code>gis_wsp</code> datasets. Like <code>gis_prob_storm_surge</code>, we will need <code>datetime</code>, but we will not need <code>key</code>. The last parameter is <code>res</code> (resolution). Valid values are 5, 0.5, and 0.1 degrees. The default is all three. Not all resolutions will be available for all storms.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/args">args</a></span>(gis_wsp)</a></code></pre></div>
<pre><code>## function (datetime, res = c(5, 0.5, 0.1)) 
## NULL</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" data-line-number="1"><span class="co"># List of datasets for 5-degree resolution</span></a>
<a class="sourceLine" id="cb22-2" data-line-number="2"><span class="kw"><a href="../reference/gis_wsp.html">gis_wsp</a></span>(<span class="dt">datetime =</span> datetime, <span class="dt">res =</span> <span class="fl">0.5</span>)</a></code></pre></div>
<pre><code>## [1] "https://www.nhc.noaa.gov/gis/forecast/archive/2016100706_wsp_120hrhalfDeg.zip"</code></pre>
</div>
</div>
<div id="downloading-data" class="section level4">
<h4 class="hasAnchor">
<a href="#downloading-data" class="anchor"></a>Downloading Data</h4>
<p>Now that we’ve explored the various functions, let’s go about downloading the datasets to plot. For efficiency, I use a lot of <code>purrr</code> mapping functions here, loading each step into one variable.</p>
<p>First, I want to load all of my URLs into one vector.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" data-line-number="1"><span class="co"># Get URLs of GIS datasets to analyze</span></a>
<a class="sourceLine" id="cb24-2" data-line-number="2">urls &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(</a>
<a class="sourceLine" id="cb24-3" data-line-number="3">  <span class="co"># Advisory package</span></a>
<a class="sourceLine" id="cb24-4" data-line-number="4">  <span class="kw"><a href="../reference/gis_advisory.html">gis_advisory</a></span>(<span class="dt">key =</span> key, <span class="dt">advisory =</span> adv), </a>
<a class="sourceLine" id="cb24-5" data-line-number="5">  </a>
<a class="sourceLine" id="cb24-6" data-line-number="6">  <span class="co"># Wind field (initial and forecast) package</span></a>
<a class="sourceLine" id="cb24-7" data-line-number="7">  <span class="kw"><a href="../reference/gis_windfield.html">gis_windfield</a></span>(<span class="dt">key =</span> key, <span class="dt">advisory =</span> adv), </a>
<a class="sourceLine" id="cb24-8" data-line-number="8">  </a>
<a class="sourceLine" id="cb24-9" data-line-number="9">  <span class="co"># Storm surge probability package</span></a>
<a class="sourceLine" id="cb24-10" data-line-number="10">  <span class="kw"><a href="../reference/gis_prob_storm_surge.html">gis_prob_storm_surge</a></span>(</a>
<a class="sourceLine" id="cb24-11" data-line-number="11">    <span class="dt">key =</span> key, </a>
<a class="sourceLine" id="cb24-12" data-line-number="12">    <span class="dt">products =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">psurge =</span> <span class="dv">5</span>), </a>
<a class="sourceLine" id="cb24-13" data-line-number="13">    <span class="dt">datetime =</span> datetime</a>
<a class="sourceLine" id="cb24-14" data-line-number="14">  ), </a>
<a class="sourceLine" id="cb24-15" data-line-number="15">  </a>
<a class="sourceLine" id="cb24-16" data-line-number="16">  <span class="co"># Wind speed probability package</span></a>
<a class="sourceLine" id="cb24-17" data-line-number="17">  <span class="kw"><a href="../reference/gis_wsp.html">gis_wsp</a></span>(<span class="dt">datetime =</span> datetime, <span class="dt">res =</span> <span class="fl">0.5</span>)</a>
<a class="sourceLine" id="cb24-18" data-line-number="18">)</a></code></pre></div>
<p>Previously, <code>gis_download</code> would download the datasets, extract the shapefiles and convert them, if possible, into dataframes. Thankfully, this is no longer necessary with various improvements in the <code>sp</code> and <code>ggplot2</code> packages. Now, the <code>gis_download</code> function will only download the zip files into a specified directory. For this vignette, we’ll use a temporary directory, <code>tempdir</code>.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1"><span class="co"># Set our download directory</span></a>
<a class="sourceLine" id="cb25-2" data-line-number="2">destdir &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/tempfile">tempdir</a></span>()</a>
<a class="sourceLine" id="cb25-3" data-line-number="3"></a>
<a class="sourceLine" id="cb25-4" data-line-number="4"><span class="co"># Download datasets</span></a>
<a class="sourceLine" id="cb25-5" data-line-number="5">file_list &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb25-6" data-line-number="6"><span class="st">  </span>urls <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb25-7" data-line-number="7"><span class="st">  </span>purrr<span class="op">::</span><span class="kw"><a href="https://purrr.tidyverse.org/reference/map.html">map</a></span>(gis_download, destdir) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb25-8" data-line-number="8"><span class="st">  </span>purrr<span class="op">::</span><span class="kw"><a href="https://purrr.tidyverse.org/reference/flatten.html">flatten_chr</a></span>()</a>
<a class="sourceLine" id="cb25-9" data-line-number="9"></a>
<a class="sourceLine" id="cb25-10" data-line-number="10">file_list</a></code></pre></div>
<pre><code>##  [1] "al142016-037_5day_lin.dbf"                
##  [2] "al142016-037_5day_pgn.dbf"                
##  [3] "al142016-037_5day_pts.dbf"                
##  [4] "al142016-037_ww_wwlin.dbf"                
##  [5] "al142016-037_5day_lin.prj"                
##  [6] "al142016-037_5day_pgn.prj"                
##  [7] "al142016-037_5day_pts.prj"                
##  [8] "al142016-037_ww_wwlin.prj"                
##  [9] "al142016-037_5day_lin.shp"                
## [10] "al142016-037_5day_pgn.shp"                
## [11] "al142016-037_5day_pts.shp"                
## [12] "al142016-037_ww_wwlin.shp"                
## [13] "al142016-037_5day_lin.shx"                
## [14] "al142016-037_5day_pgn.shx"                
## [15] "al142016-037_5day_pts.shx"                
## [16] "al142016-037_ww_wwlin.shx"                
## [17] "al142016-037_5day_lin.shp.xml"            
## [18] "al142016-037_5day_pgn.shp.xml"            
## [19] "al142016-037_5day_pts.shp.xml"            
## [20] "al142016-037_ww_wwlin.shp.xml"            
## [21] "al142016_2016100706_forecastradii.dbf"    
## [22] "al142016_2016100706_forecastradii.prj"    
## [23] "al142016_2016100706_forecastradii.shp"    
## [24] "al142016_2016100706_forecastradii.shp.xml"
## [25] "al142016_2016100706_forecastradii.shx"    
## [26] "al142016_2016100706_initialradii.dbf"     
## [27] "al142016_2016100706_initialradii.prj"     
## [28] "al142016_2016100706_initialradii.shp"     
## [29] "al142016_2016100706_initialradii.shp.xml" 
## [30] "al142016_2016100706_initialradii.shx"     
## [31] "al142016_2016100706_gt5.dbf"              
## [32] "al142016_2016100706_gt5.prj"              
## [33] "al142016_2016100706_gt5.shx"              
## [34] "al142016_2016100706_gt5.txt"              
## [35] "al142016_2016100706_gt5.ave"              
## [36] "al142016_2016100706_gt5.shp.xml"          
## [37] "al142016_2016100706_gt5.shp"              
## [38] "2016100706_wsp34knt120hr_halfDeg.dbf"     
## [39] "2016100706_wsp34knt120hr_halfDeg.prj"     
## [40] "2016100706_wsp34knt120hr_halfDeg.shp"     
## [41] "2016100706_wsp34knt120hr_halfDeg.shp.xml" 
## [42] "2016100706_wsp34knt120hr_halfDeg.shx"     
## [43] "2016100706_wsp34knt120hr_halfDeg.txt"     
## [44] "2016100706_wsp50knt120hr_halfDeg.dbf"     
## [45] "2016100706_wsp50knt120hr_halfDeg.prj"     
## [46] "2016100706_wsp50knt120hr_halfDeg.shp"     
## [47] "2016100706_wsp50knt120hr_halfDeg.shp.xml" 
## [48] "2016100706_wsp50knt120hr_halfDeg.shx"     
## [49] "2016100706_wsp50knt120hr_halfDeg.txt"     
## [50] "2016100706_wsp64knt120hr_halfDeg.dbf"     
## [51] "2016100706_wsp64knt120hr_halfDeg.prj"     
## [52] "2016100706_wsp64knt120hr_halfDeg.shp"     
## [53] "2016100706_wsp64knt120hr_halfDeg.shp.xml" 
## [54] "2016100706_wsp64knt120hr_halfDeg.shx"     
## [55] "2016100706_wsp64knt120hr_halfDeg.txt"</code></pre>
<p>There are a lot of files here. Thankfully, we only care about the shapefiles (marked by the “.shp” extension). Let’s filter those.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1"><span class="co"># Filter out shapefiles</span></a>
<a class="sourceLine" id="cb27-2" data-line-number="2">shp_files &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/grep">grep</a></span>(<span class="st">".shp$"</span>, file_list, <span class="dt">value =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb27-3" data-line-number="3">shp_files</a></code></pre></div>
<pre><code>##  [1] "al142016-037_5day_lin.shp"            
##  [2] "al142016-037_5day_pgn.shp"            
##  [3] "al142016-037_5day_pts.shp"            
##  [4] "al142016-037_ww_wwlin.shp"            
##  [5] "al142016_2016100706_forecastradii.shp"
##  [6] "al142016_2016100706_initialradii.shp" 
##  [7] "al142016_2016100706_gt5.shp"          
##  [8] "2016100706_wsp34knt120hr_halfDeg.shp" 
##  [9] "2016100706_wsp50knt120hr_halfDeg.shp" 
## [10] "2016100706_wsp64knt120hr_halfDeg.shp"</code></pre>
<p>We can use <code><a href="https://www.rdocumentation.org/packages/sf/topics/st_read">sf::st_read</a></code> to read in each shapefile as a shapefile dataframe. The output is quite verbose; you can pass the parameter <code>quiet</code> as TRUE.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1"><span class="co"># Read in shapefiles</span></a>
<a class="sourceLine" id="cb29-2" data-line-number="2">shp_df &lt;-<span class="st"> </span>purrr<span class="op">::</span><span class="kw"><a href="https://purrr.tidyverse.org/reference/map.html">map</a></span>(shp_files, <span class="op">~</span><span class="st"> </span>sf<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sf/topics/st_read">st_read</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/file.path">file.path</a></span>(destdir, .x)))</a></code></pre></div>
<pre><code>## Reading layer `al142016-037_5day_lin' from data source `/tmp/RtmpJnuPnX/al142016-037_5day_lin.shp' using driver `ESRI Shapefile'
## Simple feature collection with 2 features and 7 fields
## geometry type:  LINESTRING
## dimension:      XY
## bbox:           xmin: -80.6 ymin: 27 xmax: -74.5 ymax: 33.1
## epsg (SRID):    NA
## proj4string:    +proj=longlat +a=6371200 +b=6371200 +no_defs
## Reading layer `al142016-037_5day_pgn' from data source `/tmp/RtmpJnuPnX/al142016-037_5day_pgn.shp' using driver `ESRI Shapefile'
## Simple feature collection with 2 features and 7 fields
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: -81.4783 ymin: 23.15623 xmax: -71.83253 ymax: 34.47927
## epsg (SRID):    NA
## proj4string:    +proj=longlat +a=6371200 +b=6371200 +no_defs
## Reading layer `al142016-037_5day_pts' from data source `/tmp/RtmpJnuPnX/al142016-037_5day_pts.shp' using driver `ESRI Shapefile'
## Simple feature collection with 14 features and 23 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -80.6 ymin: 27 xmax: -74.5 ymax: 33.1
## epsg (SRID):    NA
## proj4string:    +proj=longlat +a=6371200 +b=6371200 +no_defs
## Reading layer `al142016-037_ww_wwlin' from data source `/tmp/RtmpJnuPnX/al142016-037_ww_wwlin.shp' using driver `ESRI Shapefile'
## Simple feature collection with 10 features and 8 fields
## geometry type:  LINESTRING
## dimension:      XY
## bbox:           xmin: -83.17 ymin: 23.75 xmax: -76.13 ymax: 34.44
## epsg (SRID):    NA
## proj4string:    +proj=longlat +a=6371200 +b=6371200 +no_defs
## Reading layer `al142016_2016100706_forecastradii' from data source `/tmp/RtmpJnuPnX/al142016_2016100706_forecastradii.shp' using driver `ESRI Shapefile'
## Simple feature collection with 16 features and 11 fields
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: -82.89683 ymin: 25.85747 xmax: -71.57337 ymax: 35.94275
## epsg (SRID):    NA
## proj4string:    +proj=longlat +a=6371200 +b=6371200 +no_defs
## Reading layer `al142016_2016100706_initialradii' from data source `/tmp/RtmpJnuPnX/al142016_2016100706_initialradii.shp' using driver `ESRI Shapefile'
## Simple feature collection with 3 features and 11 fields
## geometry type:  POLYGON
## dimension:      XY
## bbox:           xmin: -82.01794 ymin: 26.16483 xmax: -77.13445 ymax: 30.62306
## epsg (SRID):    NA
## proj4string:    +proj=longlat +a=6371200 +b=6371200 +no_defs
## Reading layer `al142016_2016100706_gt5' from data source `/tmp/RtmpJnuPnX/al142016_2016100706_gt5.shp' using driver `ESRI Shapefile'
## Simple feature collection with 99 features and 2 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -82.75004 ymin: 27.54227 xmax: -76.7436 ymax: 35.57721
## epsg (SRID):    NA
## proj4string:    +proj=longlat +a=6371200 +b=6371200 +no_defs
## Reading layer `2016100706_wsp34knt120hr_halfDeg' from data source `/tmp/RtmpJnuPnX/2016100706_wsp34knt120hr_halfDeg.shp' using driver `ESRI Shapefile'
## Simple feature collection with 4367 features and 2 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -87 ymin: 6 xmax: 128.5 ymax: 43.5
## epsg (SRID):    NA
## proj4string:    +proj=longlat +a=6371.229 +b=6371.229 +no_defs
## Reading layer `2016100706_wsp50knt120hr_halfDeg' from data source `/tmp/RtmpJnuPnX/2016100706_wsp50knt120hr_halfDeg.shp' using driver `ESRI Shapefile'
## Simple feature collection with 2302 features and 2 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -86 ymin: 8 xmax: 127 ymax: 42
## epsg (SRID):    NA
## proj4string:    +proj=longlat +a=6371.229 +b=6371.229 +no_defs
## Reading layer `2016100706_wsp64knt120hr_halfDeg' from data source `/tmp/RtmpJnuPnX/2016100706_wsp64knt120hr_halfDeg.shp' using driver `ESRI Shapefile'
## Simple feature collection with 1367 features and 2 fields
## geometry type:  POINT
## dimension:      XY
## bbox:           xmin: -83 ymin: 12 xmax: 126.5 ymax: 39
## epsg (SRID):    NA
## proj4string:    +proj=longlat +a=6371.229 +b=6371.229 +no_defs</code></pre>
<p>And, while not necessary, I will rename the list of dataframes, <code>shp_df</code>, to the names of their respective shapefiles minus the file extension.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1"><span class="co"># Create names from shapefiles by removing file extension</span></a>
<a class="sourceLine" id="cb31-2" data-line-number="2">shp_df &lt;-<span class="st"> </span>rlang<span class="op">::</span><span class="kw"><a href="https://rlang.r-lib.org/reference/set_names.html">set_names</a></span>(shp_df, <span class="dt">nm =</span> tools<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/tools/topics/fileutils">file_path_sans_ext</a></span>(shp_files))</a>
<a class="sourceLine" id="cb31-3" data-line-number="3"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/names">names</a></span>(shp_df)</a></code></pre></div>
<pre><code>##  [1] "al142016-037_5day_lin"            
##  [2] "al142016-037_5day_pgn"            
##  [3] "al142016-037_5day_pts"            
##  [4] "al142016-037_ww_wwlin"            
##  [5] "al142016_2016100706_forecastradii"
##  [6] "al142016_2016100706_initialradii" 
##  [7] "al142016_2016100706_gt5"          
##  [8] "2016100706_wsp34knt120hr_halfDeg" 
##  [9] "2016100706_wsp50knt120hr_halfDeg" 
## [10] "2016100706_wsp64knt120hr_halfDeg"</code></pre>
<p>This next stop is also not necessary. I actually found it a bit broad and rarely used it but will leave it here as an example.</p>
<p>Each shapefile has a bounding box; this box is a zoomed-in coordinate map of each dataset. We can access the bounding box of each dataset with the <code><a href="https://www.rdocumentation.org/packages/sf/topics/st_bbox">sf::st_bbox</a></code> function.</p>
<p>For example, in our advisory package we have the forecast cones (a polygon shapefile). Let’s see what the bounding box is for that dataset.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1">sf<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sf/topics/st_bbox">st_bbox</a></span>(shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pgn</span><span class="st">`</span>)</a></code></pre></div>
<pre><code>##      xmin      ymin      xmax      ymax 
## -81.47830  23.15623 -71.83253  34.47927</code></pre>
<p>Our data is contained between approximately 71°W and 81°W (note the negatives – the western hemisphere), and between 23°N and 34°N. Let’s see where that is.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1">p <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb35-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">coord_sf</a></span>(</a>
<a class="sourceLine" id="cb35-3" data-line-number="3">    <span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(</a>
<a class="sourceLine" id="cb35-4" data-line-number="4">      sf<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sf/topics/st_bbox">st_bbox</a></span>(shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pgn</span><span class="st">`</span>)<span class="op">$</span>xmin, </a>
<a class="sourceLine" id="cb35-5" data-line-number="5">      sf<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sf/topics/st_bbox">st_bbox</a></span>(shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pgn</span><span class="st">`</span>)<span class="op">$</span>xmax</a>
<a class="sourceLine" id="cb35-6" data-line-number="6">    ), </a>
<a class="sourceLine" id="cb35-7" data-line-number="7">    <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(</a>
<a class="sourceLine" id="cb35-8" data-line-number="8">      sf<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sf/topics/st_bbox">st_bbox</a></span>(shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pgn</span><span class="st">`</span>)<span class="op">$</span>ymin, </a>
<a class="sourceLine" id="cb35-9" data-line-number="9">      sf<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sf/topics/st_bbox">st_bbox</a></span>(shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pgn</span><span class="st">`</span>)<span class="op">$</span>ymax</a>
<a class="sourceLine" id="cb35-10" data-line-number="10">    )</a>
<a class="sourceLine" id="cb35-11" data-line-number="11">  )</a></code></pre></div>
<p><img src="gis_data_files/figure-html/zoom-base-plot-1.png" width="672" style="display: block; margin: auto;"></p>
<p>Nice!</p>
<p>I want to find the largest bounding box within the datasets for my map. For this, I calculate the area for each box of each dataset, identify which has the largest area then extract the bounding box for that dataset.</p>
<p>Notice I only search the advisory package datasets for a bounding box. The probability datasets may contain data for other cyclones across the world making our bounding box (and subsequent maps) quite wide. I have no interest in that so kept the focus only on Matthew.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" data-line-number="1"><span class="co"># Find which shapefile has the largest bounding box. Proability datasets are </span></a>
<a class="sourceLine" id="cb36-2" data-line-number="2"><span class="co"># excluded as they may contain data for other cyclones. This may depend on </span></a>
<a class="sourceLine" id="cb36-3" data-line-number="3"><span class="co"># the storm.</span></a>
<a class="sourceLine" id="cb36-4" data-line-number="4">x &lt;-<span class="st"> </span>purrr<span class="op">::</span><span class="kw"><a href="https://purrr.tidyverse.org/reference/map.html">map</a></span>(shp_df[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>)], sf<span class="op">::</span>st_bbox) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb36-5" data-line-number="5"><span class="st">  </span><span class="co"># Calculate the coverage for each bbox</span></a>
<a class="sourceLine" id="cb36-6" data-line-number="6"><span class="st">  </span>purrr<span class="op">::</span><span class="kw"><a href="https://purrr.tidyverse.org/reference/map.html">map_dbl</a></span>(<span class="op">~</span>(.x<span class="op">$</span>xmax <span class="op">-</span><span class="st"> </span>.x<span class="op">$</span>xmin) <span class="op">*</span><span class="st"> </span>(.x<span class="op">$</span>ymax <span class="op">-</span><span class="st"> </span>.x<span class="op">$</span>ymin)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb36-7" data-line-number="7"><span class="st">  </span><span class="co"># Extract which shapefile has the largest coverage area </span></a>
<a class="sourceLine" id="cb36-8" data-line-number="8"><span class="st">  </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.max</a></span>()</a>
<a class="sourceLine" id="cb36-9" data-line-number="9"></a>
<a class="sourceLine" id="cb36-10" data-line-number="10"><span class="co"># Get the bounding box</span></a>
<a class="sourceLine" id="cb36-11" data-line-number="11">(bbox &lt;-<span class="st"> </span>sf<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/sf/topics/st_bbox">st_bbox</a></span>(shp_df[[x]]))</a></code></pre></div>
<pre><code>##      xmin      ymin      xmax      ymax 
## -81.47830  23.15623 -71.83253  34.47927</code></pre>
</div>
</div>
<div id="advisory-package" class="section level3">
<h3 class="hasAnchor">
<a href="#advisory-package" class="anchor"></a>Advisory Package</h3>
<p>Each dataset returned by the <code>gis_advisory</code> function should contain four datasets.</p>
<ul>
<li><p>5day_lin - A line plot of the forecast (previous track not included)</p></li>
<li><p>5day_pgn - A polygon identifying the forecast cone or area the center of the storm could travel within a given period of time.</p></li>
<li><p>5day_pts - A points dataframe identifying the current location and each forecast position.</p></li>
<li><p>ww_wwlin - Any existing watches and warnings.</p></li>
</ul>
<p>Let’s go ahead and create a plot and then I’ll explain in detail what I’m doing here.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" data-line-number="1">p <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb38-2" data-line-number="2"><span class="st">  </span><span class="co"># Despite two forecast periods, the cones are identical for both.</span></a>
<a class="sourceLine" id="cb38-3" data-line-number="3"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb38-4" data-line-number="4">    <span class="dt">data =</span> shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_lin</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb38-5" data-line-number="5">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">geometry =</span> geometry)</a>
<a class="sourceLine" id="cb38-6" data-line-number="6">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb38-7" data-line-number="7"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span>(</a>
<a class="sourceLine" id="cb38-8" data-line-number="8">    <span class="dt">data =</span> shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pts</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb38-9" data-line-number="9">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(</a>
<a class="sourceLine" id="cb38-10" data-line-number="10">      <span class="dt">x =</span> .data<span class="op">$</span>LON,</a>
<a class="sourceLine" id="cb38-11" data-line-number="11">      <span class="dt">y =</span> .data<span class="op">$</span>LAT,</a>
<a class="sourceLine" id="cb38-12" data-line-number="12">      <span class="dt">fill =</span> .data<span class="op">$</span>DVLBL,</a>
<a class="sourceLine" id="cb38-13" data-line-number="13">      <span class="dt">shape =</span> .data<span class="op">$</span>DVLBL,</a>
<a class="sourceLine" id="cb38-14" data-line-number="14">      <span class="dt">size =</span> .data<span class="op">$</span>MAXWIND</a>
<a class="sourceLine" id="cb38-15" data-line-number="15">    )</a>
<a class="sourceLine" id="cb38-16" data-line-number="16">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb38-17" data-line-number="17"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb38-18" data-line-number="18">    <span class="dt">data =</span> shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_ww_wwlin</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb38-19" data-line-number="19">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(</a>
<a class="sourceLine" id="cb38-20" data-line-number="20">      <span class="dt">geometry =</span> .data<span class="op">$</span>geometry,</a>
<a class="sourceLine" id="cb38-21" data-line-number="21">      <span class="dt">color =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(.data<span class="op">$</span>TCWW)</a>
<a class="sourceLine" id="cb38-22" data-line-number="22">    ),</a>
<a class="sourceLine" id="cb38-23" data-line-number="23">    <span class="dt">size =</span> <span class="dv">2</span>,</a>
<a class="sourceLine" id="cb38-24" data-line-number="24">    <span class="co"># key_glyph available as of ggplot 3.2.0</span></a>
<a class="sourceLine" id="cb38-25" data-line-number="25">    <span class="dt">key_glyph =</span> draw_key_path</a>
<a class="sourceLine" id="cb38-26" data-line-number="26">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb38-27" data-line-number="27"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb38-28" data-line-number="28">    <span class="dt">data =</span> shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pgn</span><span class="st">`</span>, </a>
<a class="sourceLine" id="cb38-29" data-line-number="29">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(</a>
<a class="sourceLine" id="cb38-30" data-line-number="30">      <span class="dt">geometry =</span> geometry,</a>
<a class="sourceLine" id="cb38-31" data-line-number="31">    ), </a>
<a class="sourceLine" id="cb38-32" data-line-number="32">    <span class="dt">color =</span> <span class="st">"antiquewhite3"</span>, </a>
<a class="sourceLine" id="cb38-33" data-line-number="33">    <span class="dt">fill =</span> <span class="st">"transparent"</span></a>
<a class="sourceLine" id="cb38-34" data-line-number="34">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb38-35" data-line-number="35"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_shape_manual</a></span>(<span class="dt">name =</span> <span class="st">"Status"</span>, <span class="dt">values =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="dv">21</span>, <span class="dv">4</span>))) <span class="op">+</span></a>
<a class="sourceLine" id="cb38-36" data-line-number="36"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_hue.html">scale_fill_discrete</a></span>(<span class="dt">name =</span> <span class="st">"Status"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb38-37" data-line-number="37"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_size.html">scale_size_continuous</a></span>(<span class="dt">name =</span> <span class="st">"Wind (kts)"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb38-38" data-line-number="38"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_color_manual</a></span>(</a>
<a class="sourceLine" id="cb38-39" data-line-number="39">    <span class="dt">name =</span> <span class="st">"Watches/Warnings"</span>,</a>
<a class="sourceLine" id="cb38-40" data-line-number="40">    <span class="dt">limits =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"TWA"</span>, <span class="st">"TWR"</span>, <span class="st">"HWA"</span>, <span class="st">"HWR"</span>),</a>
<a class="sourceLine" id="cb38-41" data-line-number="41">    <span class="dt">values =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"orange"</span>, <span class="st">"blue"</span>, <span class="st">"pink"</span>, <span class="st">"red"</span>),</a>
<a class="sourceLine" id="cb38-42" data-line-number="42">    <span class="dt">labels =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(</a>
<a class="sourceLine" id="cb38-43" data-line-number="43">      <span class="st">"Tropical Storm Watch"</span>,</a>
<a class="sourceLine" id="cb38-44" data-line-number="44">      <span class="st">"Tropical Storm Warning"</span>,</a>
<a class="sourceLine" id="cb38-45" data-line-number="45">      <span class="st">"Hurricane Watch"</span>,</a>
<a class="sourceLine" id="cb38-46" data-line-number="46">      <span class="st">"Hurricane Warning"</span></a>
<a class="sourceLine" id="cb38-47" data-line-number="47">    ),</a>
<a class="sourceLine" id="cb38-48" data-line-number="48">    <span class="dt">drop =</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb38-49" data-line-number="49">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb38-50" data-line-number="50"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">coord_sf</a></span>(</a>
<a class="sourceLine" id="cb38-51" data-line-number="51">    <span class="co"># Give some more breathing room on the x axis</span></a>
<a class="sourceLine" id="cb38-52" data-line-number="52">    <span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(scales<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/scales/topics/expand_range">expand_range</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(bbox<span class="op">$</span>xmax, bbox<span class="op">$</span>xmin), <span class="dt">mul =</span> <span class="fl">0.25</span>)), </a>
<a class="sourceLine" id="cb38-53" data-line-number="53">    <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(</a>
<a class="sourceLine" id="cb38-54" data-line-number="54">      bbox<span class="op">$</span>ymin, </a>
<a class="sourceLine" id="cb38-55" data-line-number="55">      bbox<span class="op">$</span>ymax</a>
<a class="sourceLine" id="cb38-56" data-line-number="56">    ), </a>
<a class="sourceLine" id="cb38-57" data-line-number="57">    <span class="dt">expand =</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb38-58" data-line-number="58">  ) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb38-59" data-line-number="59"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/guides.html">guides</a></span>(</a>
<a class="sourceLine" id="cb38-60" data-line-number="60">    <span class="dt">color =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/guide_legend.html">guide_legend</a></span>(<span class="dt">nrow =</span> <span class="dv">2</span>, <span class="dt">byrow =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb38-61" data-line-number="61">  ) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb38-62" data-line-number="62"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(</a>
<a class="sourceLine" id="cb38-63" data-line-number="63">    <span class="dt">panel.ontop =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb38-64" data-line-number="64">    <span class="dt">panel.background =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span>(), </a>
<a class="sourceLine" id="cb38-65" data-line-number="65">    <span class="dt">panel.grid.major =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_line</a></span>(<span class="dt">color =</span> <span class="st">"lightgray"</span>, <span class="dt">size =</span> <span class="fl">0.1</span>),</a>
<a class="sourceLine" id="cb38-66" data-line-number="66">    <span class="dt">legend.position =</span> <span class="st">"bottom"</span>, </a>
<a class="sourceLine" id="cb38-67" data-line-number="67">    <span class="dt">legend.box =</span> <span class="st">"vertical"</span></a>
<a class="sourceLine" id="cb38-68" data-line-number="68">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb38-69" data-line-number="69"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span>(<span class="dt">title =</span> <span class="st">"Hurricane Matthew Advisory #37"</span>)</a></code></pre></div>
<p><img src="gis_data_files/figure-html/plot-gis-advisory-1.png" width="672" style="display: block; margin: auto;"></p>
<div id="forecast-line" class="section level4">
<h4 class="hasAnchor">
<a href="#forecast-line" class="anchor"></a>Forecast Line</h4>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_lin</span><span class="st">`</span>)</a></code></pre></div>
<pre><code>## Classes 'sf' and 'data.frame':   2 obs. of  8 variables:
##  $ STORMNAME: Factor w/ 1 level "MATTHEW": 1 1
##  $ STORMTYPE: Factor w/ 1 level "HU": 1 1
##  $ ADVDATE  : Factor w/ 1 level "161007/0900": 1 1
##  $ ADVISNUM : Factor w/ 1 level "37": 1 1
##  $ STORMNUM : num  14 14
##  $ FCSTPRD  : num  72 120
##  $ BASIN    : Factor w/ 1 level "al": 1 1
##  $ geometry :sfc_LINESTRING of length 2; first list element:  'XY' num [1:6, 1:2] -80 -80.6 -80.5 -79.2 -77.7 ...
##  - attr(*, "sf_column")= chr "geometry"
##  - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA
##   ..- attr(*, "names")= chr  "STORMNAME" "STORMTYPE" "ADVDATE" "ADVISNUM" ...</code></pre>
<p>Plotting the forecast line is nothing fancy though you could define different linestyles depending on the status of the storm (<code>STORMTYPE</code>) or the forecast period (<code>FCSTPRD</code>). Additional variables are pretty self-explanatory; <code>STORMNAME</code>, <code>ADVDATE</code>, <code>ADVISNUM</code>, <code>STORMNUM</code>, and <code>BASIN</code>.</p>
<div class="sourceCode" id="cb41" startfrom="3"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><a class="sourceLine" id="cb41-3" data-line-number="3">  <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb41-4" data-line-number="4">    <span class="dt">data =</span> shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_lin</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb41-5" data-line-number="5">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">geometry =</span> geometry)</a>
<a class="sourceLine" id="cb41-6" data-line-number="6">  ) <span class="op">+</span></a></code></pre></div>
</div>
<div id="forecast-points" class="section level4">
<h4 class="hasAnchor">
<a href="#forecast-points" class="anchor"></a>Forecast Points</h4>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pts</span><span class="st">`</span>)</a></code></pre></div>
<pre><code>## Classes 'sf' and 'data.frame':   14 obs. of  24 variables:
##  $ STORMNAME: Factor w/ 1 level "MATTHEW": 1 1 1 1 1 1 1 1 1 1 ...
##  $ STORMTYPE: Factor w/ 1 level "HU": 1 1 1 1 1 1 1 1 1 1 ...
##  $ ADVDATE  : Factor w/ 1 level "161007/0900": 1 1 1 1 1 1 1 1 1 1 ...
##  $ ADVISNUM : Factor w/ 1 level "37": 1 1 1 1 1 1 1 1 1 1 ...
##  $ STORMNUM : num  14 14 14 14 14 14 14 14 14 14 ...
##  $ FCSTPRD  : num  72 72 72 72 72 72 120 120 120 120 ...
##  $ BASIN    : Factor w/ 1 level "al": 1 1 1 1 1 1 1 1 1 1 ...
##  $ LAT      : num  28.2 29.6 31.5 32.6 33.1 31.5 28.2 29.6 31.5 32.6 ...
##  $ LON      : num  -80 -80.6 -80.5 -79.2 -77.7 -74.5 -80 -80.6 -80.5 -79.2 ...
##  $ VALIDTIME: Factor w/ 8 levels "07/0900","07/1800",..: 1 2 3 4 5 6 1 2 3 4 ...
##  $ TAU      : num  3 12 24 36 48 72 3 12 24 36 ...
##  $ MAXWIND  : num  105 100 90 80 65 50 105 100 90 80 ...
##  $ GUST     : num  130 120 110 100 80 60 130 120 110 100 ...
##  $ MSLP     : num  938 9999 9999 9999 9999 ...
##  $ TCDVLP   : Factor w/ 3 levels "Hurricane","Major Hurricane",..: 2 2 1 1 1 3 2 2 1 1 ...
##  $ DVLBL    : Factor w/ 3 levels "H","M","S": 2 2 1 1 1 3 2 2 1 1 ...
##  $ SSNUM    : num  3 3 2 1 1 0 3 3 2 1 ...
##  $ TCDIR    : num  330 9999 9999 9999 9999 ...
##  $ TCSPD    : num  11 9999 9999 9999 9999 ...
##  $ DATELBL  : Factor w/ 8 levels "2:00 AM Mon",..: 8 6 2 7 3 1 8 6 2 7 ...
##  $ FLDATELBL: Factor w/ 8 levels "2016-10-07 2:00 PM Fri EDT",..: 2 1 3 4 5 6 2 1 3 4 ...
##  $ TIMEZONE : Factor w/ 1 level "EDT": 1 1 1 1 1 1 1 1 1 1 ...
##  $ STORMSRC : Factor w/ 1 level "Tropical Cyclone": 1 1 1 1 1 1 1 1 1 1 ...
##  $ geometry :sfc_POINT of length 14; first list element:  'XY' num  -80 28.2
##  - attr(*, "sf_column")= chr "geometry"
##  - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA NA NA ...
##   ..- attr(*, "names")= chr  "STORMNAME" "STORMTYPE" "ADVDATE" "ADVISNUM" ...</code></pre>
<p>The points shapefile contains the same variables as the line shapefile and more. I am unable to find official documentation so let me give my best here to explain some of the added variables.</p>
<ul>
<li><p><code>TAU</code> - This appears to be the time period in hours for each forecast point, gruoped by <code>FCSTPRD</code></p></li>
<li><p><code>MSLP</code> - Forecast minimum sea level pressure. “9999” values simply indicate no forecast MSLP was provided.</p></li>
<li><p><code>TCDVLP</code> - The forecast status of the cyclone.</p></li>
<li><p><code>DVLBL</code> - A shorter label for <code>TCDVLP</code></p></li>
<li><p><code>SSNUM</code> - Sorry, no idea…</p></li>
<li><p><code>TCDIR</code> - Foreward direction of the storm</p></li>
<li><p><code>TCSPD</code> - Foreward speed of the storm</p></li>
</ul>
<div class="sourceCode" id="cb44" startfrom="7"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><a class="sourceLine" id="cb44-7" data-line-number="7">  <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span>(</a>
<a class="sourceLine" id="cb44-8" data-line-number="8">    <span class="dt">data =</span> shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pts</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb44-9" data-line-number="9">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(</a>
<a class="sourceLine" id="cb44-10" data-line-number="10">      <span class="dt">x =</span> .data<span class="op">$</span>LON,</a>
<a class="sourceLine" id="cb44-11" data-line-number="11">      <span class="dt">y =</span> .data<span class="op">$</span>LAT,</a>
<a class="sourceLine" id="cb44-12" data-line-number="12">      <span class="dt">fill =</span> .data<span class="op">$</span>DVLBL,</a>
<a class="sourceLine" id="cb44-13" data-line-number="13">      <span class="dt">shape =</span> .data<span class="op">$</span>DVLBL,</a>
<a class="sourceLine" id="cb44-14" data-line-number="14">      <span class="dt">size =</span> .data<span class="op">$</span>MAXWIND</a>
<a class="sourceLine" id="cb44-15" data-line-number="15">    )</a>
<a class="sourceLine" id="cb44-16" data-line-number="16">  ) <span class="op">+</span></a></code></pre></div>
<p>Since we have the added variables <code>LAT</code> and <code>LON</code>, and I wanted to customize the aesthetics a bit, I chose to use the layer <code>geom_point</code>. I set fill and shape to <code>DVLBL</code> and size to <code>MAXWIND</code>. I also wanted to customize the appearance of each point and, since I’ll be using the color aesthetic for watches and warnings as well, I needed to customize these scales.</p>
<div class="sourceCode" id="cb45" startfrom="35"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><a class="sourceLine" id="cb45-35" data-line-number="35">  <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_shape_manual</a></span>(<span class="dt">name =</span> <span class="st">"Status"</span>, <span class="dt">values =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="dv">21</span>, <span class="dv">4</span>))) <span class="op">+</span></a>
<a class="sourceLine" id="cb45-36" data-line-number="36"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_hue.html">scale_fill_discrete</a></span>(<span class="dt">name =</span> <span class="st">"Status"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb45-37" data-line-number="37"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_size.html">scale_size_continuous</a></span>(<span class="dt">name =</span> <span class="st">"Wind (kts)"</span>) <span class="op">+</span></a></code></pre></div>
</div>
<div id="watches-and-warnings" class="section level4">
<h4 class="hasAnchor">
<a href="#watches-and-warnings" class="anchor"></a>Watches and Warnings</h4>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_ww_wwlin</span><span class="st">`</span>)</a></code></pre></div>
<pre><code>## Classes 'sf' and 'data.frame':   10 obs. of  9 variables:
##  $ STORMNAME: Factor w/ 1 level "MATTHEW": 1 1 1 1 1 1 1 1 1 1
##  $ STORMTYPE: Factor w/ 1 level "HU": 1 1 1 1 1 1 1 1 1 1
##  $ ADVDATE  : Factor w/ 1 level "161007/0900": 1 1 1 1 1 1 1 1 1 1
##  $ ADVISNUM : Factor w/ 1 level "37": 1 1 1 1 1 1 1 1 1 1
##  $ STORMNUM : num  14 14 14 14 14 14 14 14 14 14
##  $ FCSTPRD  : num  120 120 120 120 120 120 120 120 120 120
##  $ BASIN    : Factor w/ 1 level "al": 1 1 1 1 1 1 1 1 1 1
##  $ TCWW     : Factor w/ 3 levels "HWR","TWA","TWR": 1 1 1 1 1 1 3 3 3 2
##  $ geometry :sfc_LINESTRING of length 10; first list element:  'XY' num [1:5, 1:2] -77.6 -77.7 -78.2 -78.4 -77.6 ...
##  - attr(*, "sf_column")= chr "geometry"
##  - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA
##   ..- attr(*, "names")= chr  "STORMNAME" "STORMTYPE" "ADVDATE" "ADVISNUM" ...</code></pre>
<p>In the watches and warnings dataset we have the <code>TCWW</code> variable which identifies the watch/warning issued for each line. There are only four possible candidates here:</p>
<ul>
<li><p><code>TWA</code> - Tropical storm watch</p></li>
<li><p><code>TWR</code> - Tropical storm warning</p></li>
<li><p><code>HWA</code> - Hurricane watch</p></li>
<li><p><code>HWR</code> - Hurricane warning</p></li>
</ul>
<p>I use the <code>geom_sf</code> layer and set the color aesthetic. I also increased the size of the lines to stand out a bit and, with the introduction of key glyphs in ggplot 3.2.0, changed the legend style.</p>
<div class="sourceCode" id="cb48" startfrom="17"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><a class="sourceLine" id="cb48-17" data-line-number="17">  <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb48-18" data-line-number="18">    <span class="dt">data =</span> shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_ww_wwlin</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb48-19" data-line-number="19">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(</a>
<a class="sourceLine" id="cb48-20" data-line-number="20">      <span class="dt">geometry =</span> .data<span class="op">$</span>geometry,</a>
<a class="sourceLine" id="cb48-21" data-line-number="21">      <span class="dt">color =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(.data<span class="op">$</span>TCWW)</a>
<a class="sourceLine" id="cb48-22" data-line-number="22">    ),</a>
<a class="sourceLine" id="cb48-23" data-line-number="23">    <span class="dt">size =</span> <span class="dv">2</span>,</a>
<a class="sourceLine" id="cb48-24" data-line-number="24">    <span class="co"># key_glyph available as of ggplot 3.2.0</span></a>
<a class="sourceLine" id="cb48-25" data-line-number="25">    <span class="dt">key_glyph =</span> draw_key_path</a>
<a class="sourceLine" id="cb48-26" data-line-number="26">  ) <span class="op">+</span></a></code></pre></div>
<p>Since I’m already using color in the points layer, I needed to add an additional legend to identify the watches and warnings. I set the <code>drop</code> parameter to FALSE to ensure that all four keys show regardless of what is in the dataset.</p>
<div class="sourceCode" id="cb49" startfrom="38"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><a class="sourceLine" id="cb49-38" data-line-number="38">  <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_color_manual</a></span>(</a>
<a class="sourceLine" id="cb49-39" data-line-number="39">    <span class="dt">name =</span> <span class="st">"Watches/Warnings"</span>,</a>
<a class="sourceLine" id="cb49-40" data-line-number="40">    <span class="dt">limits =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"TWA"</span>, <span class="st">"TWR"</span>, <span class="st">"HWA"</span>, <span class="st">"HWR"</span>),</a>
<a class="sourceLine" id="cb49-41" data-line-number="41">    <span class="dt">values =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"orange"</span>, <span class="st">"blue"</span>, <span class="st">"pink"</span>, <span class="st">"red"</span>),</a>
<a class="sourceLine" id="cb49-42" data-line-number="42">    <span class="dt">labels =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(</a>
<a class="sourceLine" id="cb49-43" data-line-number="43">      <span class="st">"Tropical Storm Watch"</span>,</a>
<a class="sourceLine" id="cb49-44" data-line-number="44">      <span class="st">"Tropical Storm Warning"</span>,</a>
<a class="sourceLine" id="cb49-45" data-line-number="45">      <span class="st">"Hurricane Watch"</span>,</a>
<a class="sourceLine" id="cb49-46" data-line-number="46">      <span class="st">"Hurricane Warning"</span></a>
<a class="sourceLine" id="cb49-47" data-line-number="47">    ),</a>
<a class="sourceLine" id="cb49-48" data-line-number="48">    <span class="dt">drop =</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb49-49" data-line-number="49">  ) <span class="op">+</span></a></code></pre></div>
<p>Below, I break the legend into two rows.</p>
<div class="sourceCode" id="cb50" startfrom="59"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><a class="sourceLine" id="cb50-59" data-line-number="59">  <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/guides.html">guides</a></span>(</a>
<a class="sourceLine" id="cb50-60" data-line-number="60">    <span class="dt">color =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/guide_legend.html">guide_legend</a></span>(<span class="dt">nrow =</span> <span class="dv">2</span>, <span class="dt">byrow =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb50-61" data-line-number="61">  ) <span class="op">+</span><span class="st"> </span></a></code></pre></div>
</div>
<div id="forecast-cone" class="section level4">
<h4 class="hasAnchor">
<a href="#forecast-cone" class="anchor"></a>Forecast Cone</h4>
<p>The forecast cone is contained in the polygon dataset of the advisory package. Take a look at the structure.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pgn</span><span class="st">`</span>)</a></code></pre></div>
<pre><code>## Classes 'sf' and 'data.frame':   2 obs. of  8 variables:
##  $ STORMNAME: Factor w/ 1 level "MATTHEW": 1 1
##  $ STORMTYPE: Factor w/ 1 level "HU": 1 1
##  $ ADVDATE  : Factor w/ 1 level "161007/0900": 1 1
##  $ ADVISNUM : Factor w/ 1 level "37": 1 1
##  $ STORMNUM : num  14 14
##  $ FCSTPRD  : num  72 120
##  $ BASIN    : Factor w/ 1 level "al": 1 1
##  $ geometry :sfc_POLYGON of length 2; first list element: List of 1
##   ..$ : num [1:274, 1:2] -79.9 -80.2 -80.4 -80.6 -80.7 ...
##   ..- attr(*, "class")= chr  "XY" "POLYGON" "sfg"
##  - attr(*, "sf_column")= chr "geometry"
##  - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA
##   ..- attr(*, "names")= chr  "STORMNAME" "STORMTYPE" "ADVDATE" "ADVISNUM" ...</code></pre>
<p>The geometry should be slightly different depending on the <code>FCSTPRD</code>. However, for this dataset, that is not the case.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/identical">identical</a></span>(</a>
<a class="sourceLine" id="cb53-2" data-line-number="2">  shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pgn</span><span class="st">`</span><span class="op">$</span>geometry[<span class="dv">1</span>], </a>
<a class="sourceLine" id="cb53-3" data-line-number="3">  shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pgn</span><span class="st">`</span><span class="op">$</span>geometry[<span class="dv">2</span>]</a>
<a class="sourceLine" id="cb53-4" data-line-number="4">)</a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>I could have filled differently depending on different geometries; unfortunately it was just not possible. So I kept the <code>geom_sf</code> call simple.</p>
<div class="sourceCode" id="cb55" startfrom="27"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><a class="sourceLine" id="cb55-27" data-line-number="27">  <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb55-28" data-line-number="28">    <span class="dt">data =</span> shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pgn</span><span class="st">`</span>, </a>
<a class="sourceLine" id="cb55-29" data-line-number="29">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(</a>
<a class="sourceLine" id="cb55-30" data-line-number="30">      <span class="dt">geometry =</span> geometry,</a>
<a class="sourceLine" id="cb55-31" data-line-number="31">    ), </a>
<a class="sourceLine" id="cb55-32" data-line-number="32">    <span class="dt">color =</span> <span class="st">"antiquewhite3"</span>, </a>
<a class="sourceLine" id="cb55-33" data-line-number="33">    <span class="dt">fill =</span> <span class="st">"transparent"</span></a>
<a class="sourceLine" id="cb55-34" data-line-number="34">  ) <span class="op">+</span></a></code></pre></div>
</div>
</div>
<div id="forecast-wind-radii" class="section level3">
<h3 class="hasAnchor">
<a href="#forecast-wind-radii" class="anchor"></a>Forecast Wind Radii</h3>
<p>The forecast wind radii dataset should contain two datasets; one for the current wind radius and another for the forecast wind radii.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(shp_df<span class="op">$</span>al142016_<span class="dv">2016100706</span>_initialradii)</a></code></pre></div>
<pre><code>## Classes 'sf' and 'data.frame':   3 obs. of  12 variables:
##  $ RADII    : num  34 50 64
##  $ STORMID  : Factor w/ 1 level "al142016": 1 1 1
##  $ BASIN    : Factor w/ 1 level "AL": 1 1 1
##  $ STORMNUM : num  14 14 14
##  $ VALIDTIME: Factor w/ 1 level "2016100709": 1 1 1
##  $ SYNOPTIME: Factor w/ 1 level "2016100706": 1 1 1
##  $ TAU      : num  3 3 3
##  $ NE       : num  160 70 50
##  $ SE       : num  140 70 40
##  $ SW       : num  80 50 30
##  $ NW       : num  120 70 50
##  $ geometry :sfc_POLYGON of length 3; first list element: List of 1
##   ..$ : num [1:364, 1:2] -77.8 -77.8 -77.8 -77.7 -77.7 ...
##   ..- attr(*, "class")= chr  "XY" "POLYGON" "sfg"
##  - attr(*, "sf_column")= chr "geometry"
##  - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA NA NA ...
##   ..- attr(*, "names")= chr  "RADII" "STORMID" "BASIN" "STORMNUM" ...</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(shp_df<span class="op">$</span>al142016_<span class="dv">2016100706</span>_forecastradii)</a></code></pre></div>
<pre><code>## Classes 'sf' and 'data.frame':   16 obs. of  12 variables:
##  $ RADII    : num  34 34 34 34 34 34 50 50 50 50 ...
##  $ STORMID  : Factor w/ 1 level "al142016": 1 1 1 1 1 1 1 1 1 1 ...
##  $ BASIN    : Factor w/ 1 level "AL": 1 1 1 1 1 1 1 1 1 1 ...
##  $ STORMNUM : num  14 14 14 14 14 14 14 14 14 14 ...
##  $ VALIDTIME: Factor w/ 6 levels "2016100709","2016100718",..: 1 2 3 4 5 6 1 2 3 4 ...
##  $ SYNOPTIME: Factor w/ 1 level "2016100706": 1 1 1 1 1 1 1 1 1 1 ...
##  $ TAU      : num  3 12 24 36 48 72 3 12 24 36 ...
##  $ NE       : num  160 170 180 200 150 120 70 70 80 80 ...
##  $ SE       : num  140 140 160 160 150 150 70 70 70 70 ...
##  $ SW       : num  80 80 80 90 120 150 50 50 50 40 ...
##  $ NW       : num  120 120 110 90 90 120 70 70 70 40 ...
##  $ geometry :sfc_POLYGON of length 16; first list element: List of 1
##   ..$ : num [1:364, 1:2] -80 -79.9 -79.9 -79.8 -79.8 ...
##   ..- attr(*, "class")= chr  "XY" "POLYGON" "sfg"
##  - attr(*, "sf_column")= chr "geometry"
##  - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA NA NA NA ...
##   ..- attr(*, "names")= chr  "RADII" "STORMID" "BASIN" "STORMNUM" ...</code></pre>
<p>The “initialradii” dataset will contain up to three observations for each radii: 34 knots, 50 knots, and 64 knots. This is the expected distance from the center of circulation that minimum n-force winds can be expected.</p>
<p>The “forecastradii” can have many observations. For forecast periods up to 36 hours, all wind radii may be provided if the storm is strong enough. At 48 and 72 hours, only 34 and 50 knot wind radii are provided. No forecast wind radii are provided beyond 72 hours.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" data-line-number="1">p <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb60-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb60-3" data-line-number="3">    <span class="dt">data =</span> shp_df<span class="op">$</span>al142016_<span class="dv">2016100706</span>_forecastradii, </a>
<a class="sourceLine" id="cb60-4" data-line-number="4">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(</a>
<a class="sourceLine" id="cb60-5" data-line-number="5">      <span class="dt">geometry =</span> geometry, </a>
<a class="sourceLine" id="cb60-6" data-line-number="6">      <span class="dt">fill =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(RADII)</a>
<a class="sourceLine" id="cb60-7" data-line-number="7">    ), </a>
<a class="sourceLine" id="cb60-8" data-line-number="8">    <span class="dt">alpha =</span> <span class="fl">0.25</span></a>
<a class="sourceLine" id="cb60-9" data-line-number="9">  ) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb60-10" data-line-number="10"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb60-11" data-line-number="11">    <span class="dt">data =</span> shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_lin</span><span class="st">`</span>, </a>
<a class="sourceLine" id="cb60-12" data-line-number="12">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">geometry =</span> geometry)</a>
<a class="sourceLine" id="cb60-13" data-line-number="13">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-14" data-line-number="14"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span>(</a>
<a class="sourceLine" id="cb60-15" data-line-number="15">    <span class="dt">data =</span> shp_df<span class="op">$</span><span class="st">`</span><span class="dt">al142016-037_5day_pts</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb60-16" data-line-number="16">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(</a>
<a class="sourceLine" id="cb60-17" data-line-number="17">      <span class="dt">x =</span> .data<span class="op">$</span>LON, </a>
<a class="sourceLine" id="cb60-18" data-line-number="18">      <span class="dt">y =</span> .data<span class="op">$</span>LAT</a>
<a class="sourceLine" id="cb60-19" data-line-number="19">    )</a>
<a class="sourceLine" id="cb60-20" data-line-number="20">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-21" data-line-number="21"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">coord_sf</a></span>(</a>
<a class="sourceLine" id="cb60-22" data-line-number="22">    <span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="dv">85</span>, <span class="dv">-70</span>), </a>
<a class="sourceLine" id="cb60-23" data-line-number="23">    <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">24</span>, <span class="dv">37</span>), </a>
<a class="sourceLine" id="cb60-24" data-line-number="24">    <span class="dt">expand =</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb60-25" data-line-number="25">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-26" data-line-number="26"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_hue.html">scale_fill_discrete</a></span>(</a>
<a class="sourceLine" id="cb60-27" data-line-number="27">    <span class="dt">name =</span> <span class="st">"Forecast Wind Radii"</span></a>
<a class="sourceLine" id="cb60-28" data-line-number="28">  ) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb60-29" data-line-number="29"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(</a>
<a class="sourceLine" id="cb60-30" data-line-number="30">    <span class="dt">panel.ontop =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb60-31" data-line-number="31">    <span class="dt">panel.background =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span>(),</a>
<a class="sourceLine" id="cb60-32" data-line-number="32">    <span class="dt">panel.grid.major =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_line</a></span>(<span class="dt">color =</span> <span class="st">"lightgray"</span>, <span class="dt">size =</span> <span class="fl">0.1</span>),</a>
<a class="sourceLine" id="cb60-33" data-line-number="33">    <span class="dt">legend.position =</span> <span class="st">"bottom"</span>, </a>
<a class="sourceLine" id="cb60-34" data-line-number="34">    <span class="dt">legend.box =</span> <span class="st">"vertical"</span></a>
<a class="sourceLine" id="cb60-35" data-line-number="35">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb60-36" data-line-number="36"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span>(<span class="dt">title =</span> <span class="st">"Hurricane Matthew Forecast Wind Radii, Adv #37"</span>)</a></code></pre></div>
<p><img src="gis_data_files/figure-html/plot-forecast-wind-radii-1.png" width="672" style="display: block; margin: auto;"></p>
<p>In the plot above I take the same approach as the advisory package but only keep the line track and points to keep the graph simple. To add the forecast wind radii, I again use the <code>geom_sf</code> layer providing the <code>fill</code> aesthetic based on <code>RADII</code>. Outside of the aesthetic, I set alpha to 0.25 to make underlying radii visible as well as land areas.</p>
<div class="sourceCode" id="cb61" startfrom="2"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><a class="sourceLine" id="cb61-2" data-line-number="2">  <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb61-3" data-line-number="3">    <span class="dt">data =</span> shp_df<span class="op">$</span>al142016_<span class="dv">2016100706</span>_forecastradii, </a>
<a class="sourceLine" id="cb61-4" data-line-number="4">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(</a>
<a class="sourceLine" id="cb61-5" data-line-number="5">      <span class="dt">geometry =</span> geometry, </a>
<a class="sourceLine" id="cb61-6" data-line-number="6">      <span class="dt">fill =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(RADII)</a>
<a class="sourceLine" id="cb61-7" data-line-number="7">    ), </a>
<a class="sourceLine" id="cb61-8" data-line-number="8">    <span class="dt">alpha =</span> <span class="fl">0.25</span></a>
<a class="sourceLine" id="cb61-9" data-line-number="9">  ) <span class="op">+</span><span class="st"> </span></a></code></pre></div>
<p>The initialradii dataset was intentionally left out; as you can see it is included in the forecastradii package.</p>
</div>
<div id="wind-speed-probabilities" class="section level3">
<h3 class="hasAnchor">
<a href="#wind-speed-probabilities" class="anchor"></a>Wind Speed Probabilities</h3>
<p>As noted previously, wind speed probabilities can be provided in different resolutions. Recall that I went with the 0.5° resolution dataset. There are three packages in this dataset; proabilities of at least 34 knot winds, 50 knot winds, and 64 knot winds.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(shp_df<span class="op">$</span><span class="st">`</span><span class="dt">2016100706_wsp34knt120hr_halfDeg</span><span class="st">`</span>)</a></code></pre></div>
<pre><code>## Classes 'sf' and 'data.frame':   4367 obs. of  3 variables:
##  $ POINTID : int  90011 100011 100012 100013 10014 110014 120014 130014 140014 150014 ...
##  $ PWIND120: num  0.1 0.1 0.1 0.1 0.1 0.1 0.2 0.1 0.1 0.1 ...
##  $ geometry:sfc_POINT of length 4367; first list element:  'XY' num  104 6
##  - attr(*, "sf_column")= chr "geometry"
##  - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA
##   ..- attr(*, "names")= chr  "POINTID" "PWIND120"</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(shp_df<span class="op">$</span><span class="st">`</span><span class="dt">2016100706_wsp50knt120hr_halfDeg</span><span class="st">`</span>)</a></code></pre></div>
<pre><code>## Classes 'sf' and 'data.frame':   2302 obs. of  3 variables:
##  $ POINTID : int  10015 10016 30017 40017 130017 40018 120018 130018 140018 90019 ...
##  $ PWIND120: num  0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 ...
##  $ geometry:sfc_POINT of length 2302; first list element:  'XY' num  100 8
##  - attr(*, "sf_column")= chr "geometry"
##  - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA
##   ..- attr(*, "names")= chr  "POINTID" "PWIND120"</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(shp_df<span class="op">$</span><span class="st">`</span><span class="dt">2016100706_wsp64knt120hr_halfDeg</span><span class="st">`</span>)</a></code></pre></div>
<pre><code>## Classes 'sf' and 'data.frame':   1367 obs. of  3 variables:
##  $ POINTID : int  140023 150023 140024 150024 160024 170024 160025 170025 180025 80026 ...
##  $ PWIND120: num  0.1 0.1 0.1 0.1 0.2 0.1 0.1 0.2 0.1 0.1 ...
##  $ geometry:sfc_POINT of length 1367; first list element:  'XY' num  106 12
##  - attr(*, "sf_column")= chr "geometry"
##  - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA
##   ..- attr(*, "names")= chr  "POINTID" "PWIND120"</code></pre>
<p>Each dataset contains the variable <code>PWIND120</code>; the probability of n-speed winds up to 120 hours.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" data-line-number="1">p <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb68-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb68-3" data-line-number="3">    <span class="dt">data =</span> shp_df<span class="op">$</span><span class="st">`</span><span class="dt">2016100706_wsp64knt120hr_halfDeg</span><span class="st">`</span>,</a>
<a class="sourceLine" id="cb68-4" data-line-number="4">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(</a>
<a class="sourceLine" id="cb68-5" data-line-number="5">      <span class="dt">geometry =</span> geometry,</a>
<a class="sourceLine" id="cb68-6" data-line-number="6">      <span class="co"># A little math to add % to legend</span></a>
<a class="sourceLine" id="cb68-7" data-line-number="7">      <span class="dt">color =</span> PWIND120<span class="op">/</span><span class="dv">100</span>, </a>
<a class="sourceLine" id="cb68-8" data-line-number="8">      <span class="dt">size =</span> PWIND120, </a>
<a class="sourceLine" id="cb68-9" data-line-number="9">      <span class="dt">alpha =</span> PWIND120</a>
<a class="sourceLine" id="cb68-10" data-line-number="10">    ), </a>
<a class="sourceLine" id="cb68-11" data-line-number="11">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb68-12" data-line-number="12"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">coord_sf</a></span>(</a>
<a class="sourceLine" id="cb68-13" data-line-number="13">    <span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(</a>
<a class="sourceLine" id="cb68-14" data-line-number="14">      <span class="dv">-85</span>, </a>
<a class="sourceLine" id="cb68-15" data-line-number="15">      bbox<span class="op">$</span>xmax</a>
<a class="sourceLine" id="cb68-16" data-line-number="16">    ), </a>
<a class="sourceLine" id="cb68-17" data-line-number="17">    <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(</a>
<a class="sourceLine" id="cb68-18" data-line-number="18">      bbox<span class="op">$</span>ymin, </a>
<a class="sourceLine" id="cb68-19" data-line-number="19">      <span class="fl">37.5</span></a>
<a class="sourceLine" id="cb68-20" data-line-number="20">    ), </a>
<a class="sourceLine" id="cb68-21" data-line-number="21">    <span class="dt">expand =</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb68-22" data-line-number="22">  ) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb68-23" data-line-number="23"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_color_continuous</a></span>(</a>
<a class="sourceLine" id="cb68-24" data-line-number="24">    <span class="dt">name =</span> <span class="st">""</span>, </a>
<a class="sourceLine" id="cb68-25" data-line-number="25">    <span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="fl">0.25</span>, <span class="fl">0.75</span>), </a>
<a class="sourceLine" id="cb68-26" data-line-number="26">    <span class="dt">labels =</span> scales<span class="op">::</span>percent, </a>
<a class="sourceLine" id="cb68-27" data-line-number="27">    <span class="dt">low =</span> <span class="st">"white"</span>, </a>
<a class="sourceLine" id="cb68-28" data-line-number="28">    <span class="dt">high =</span> <span class="st">"red"</span></a>
<a class="sourceLine" id="cb68-29" data-line-number="29">  ) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb68-30" data-line-number="30"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_size.html">scale_size_continuous</a></span>(<span class="dt">guide =</span> <span class="st">"none"</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb68-31" data-line-number="31"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_alpha.html">scale_alpha_continuous</a></span>(<span class="dt">guide =</span> <span class="st">"none"</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb68-32" data-line-number="32"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(</a>
<a class="sourceLine" id="cb68-33" data-line-number="33">    <span class="dt">panel.ontop =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb68-34" data-line-number="34">    <span class="dt">panel.background =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span>(),</a>
<a class="sourceLine" id="cb68-35" data-line-number="35">    <span class="dt">panel.grid.major =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_line</a></span>(<span class="dt">color =</span> <span class="st">"lightgray"</span>, <span class="dt">size =</span> <span class="fl">0.1</span>),</a>
<a class="sourceLine" id="cb68-36" data-line-number="36">    <span class="dt">legend.position =</span> <span class="st">"bottom"</span>, </a>
<a class="sourceLine" id="cb68-37" data-line-number="37">    <span class="dt">legend.box =</span> <span class="st">"vertical"</span></a>
<a class="sourceLine" id="cb68-38" data-line-number="38">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb68-39" data-line-number="39"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span>(<span class="dt">title =</span> <span class="st">"Wind Speed Probabilities (&gt;34kts), Adv #37"</span>)</a></code></pre></div>
<p><img src="gis_data_files/figure-html/plot-wind-speed-probabilities-1.png" width="672" style="display: block; margin: auto;"></p>
<p>The plot above focuses only on the wind speed probabilities. The forecast track of the cyclone is quite clear. I made the size and alpha aesthetic based on <code>PWIND120</code> but removed those legends. I kept the color <code>aesthetic</code> which I divided by 100 to make a fraction (default is a real). With that, I applied <code><a href="https://www.rdocumentation.org/packages/scales/topics/number_format">scales::percent</a></code> to the legend to show a percentage and changed the breaks.</p>
</div>
<div id="storm-surge-probabilities" class="section level3">
<h3 class="hasAnchor">
<a href="#storm-surge-probabilities" class="anchor"></a>Storm Surge Probabilities</h3>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb69-1" data-line-number="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(shp_df<span class="op">$</span>al142016_<span class="dv">2016100706</span>_gt5)</a></code></pre></div>
<pre><code>## Classes 'sf' and 'data.frame':   99 obs. of  3 variables:
##  $ POINTID  : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ PSurge05c: num  1 2 3 4 5 6 7 8 9 10 ...
##  $ geometry :sfc_MULTIPOLYGON of length 99; first list element: List of 554
##   ..$ :List of 1
##   .. ..$ : num [1:43, 1:2] -80.3 -80.3 -80.3 -80.3 -80.3 ...
##   ..$ :List of 1
##   .. ..$ : num [1:23, 1:2] -80.3 -80.3 -80.3 -80.3 -80.3 ...
##   ..$ :List of 1
##   .. ..$ : num [1:13, 1:2] -80.3 -80.3 -80.3 -80.3 -80.3 ...
##   ..$ :List of 1
##   .. ..$ : num [1:13, 1:2] -80.3 -80.3 -80.3 -80.3 -80.3 ...
##   ..$ :List of 1
##   .. ..$ : num [1:19, 1:2] -80.3 -80.3 -80.3 -80.3 -80.3 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -82.7 -82.7 -82.7 -82.7 -82.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:11, 1:2] -82.7 -82.7 -82.7 -82.7 -82.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:11, 1:2] -82.7 -82.7 -82.7 -82.7 -82.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:11, 1:2] -82.7 -82.7 -82.7 -82.7 -82.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -82.7 -82.7 -82.7 -82.7 -82.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:17, 1:2] -82.7 -82.7 -82.7 -82.7 -82.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:45, 1:2] -80.7 -80.7 -80.7 -80.7 -80.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:15, 1:2] -80.4 -80.4 -80.4 -80.4 -80.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:7, 1:2] -80.7 -80.7 -80.7 -80.7 -80.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:11, 1:2] -82.7 -82.7 -82.7 -82.7 -82.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:13, 1:2] -80.7 -80.7 -80.7 -80.7 -80.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:9, 1:2] -80.7 -80.7 -80.7 -80.7 -80.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:19, 1:2] -80.4 -80.4 -80.4 -80.4 -80.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:9, 1:2] -80.7 -80.7 -80.7 -80.7 -80.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:11, 1:2] -80.7 -80.7 -80.7 -80.7 -80.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:67, 1:2] -82.7 -82.7 -82.7 -82.7 -82.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:33, 1:2] -82.6 -82.6 -82.6 -82.6 -82.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:15, 1:2] -80.7 -80.7 -80.7 -80.7 -80.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:11, 1:2] -80.7 -80.7 -80.7 -80.7 -80.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:9, 1:2] -80.7 -80.7 -80.7 -80.7 -80.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:15, 1:2] -80.4 -80.4 -80.4 -80.4 -80.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:17, 1:2] -80.7 -80.6 -80.6 -80.7 -80.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:13, 1:2] -80.4 -80.4 -80.4 -80.4 -80.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:11, 1:2] -80.6 -80.6 -80.6 -80.6 -80.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:15, 1:2] -80.4 -80.4 -80.4 -80.4 -80.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:9, 1:2] -80.6 -80.6 -80.7 -80.6 -80.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:7, 1:2] -80.8 -80.8 -80.8 -80.8 -80.8 ...
##   ..$ :List of 1
##   .. ..$ : num [1:87, 1:2] -82.7 -82.7 -82.7 -82.7 -82.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:29, 1:2] -80.4 -80.4 -80.4 -80.4 -80.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:9, 1:2] -82.6 -82.6 -82.6 -82.6 -82.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:49, 1:2] -80.4 -80.4 -80.4 -80.4 -80.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:9, 1:2] -80.9 -80.9 -80.9 -80.9 -80.9 ...
##   ..$ :List of 1
##   .. ..$ : num [1:19, 1:2] -80.4 -80.4 -80.4 -80.4 -80.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:121, 1:2] -82.7 -82.7 -82.7 -82.7 -82.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:29, 1:2] -80.4 -80.4 -80.4 -80.4 -80.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:9, 1:2] -80.9 -80.9 -80.9 -80.9 -80.9 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81 -81 -81 -81 -81 ...
##   ..$ :List of 1
##   .. ..$ : num [1:87, 1:2] -80.3 -80.3 -80.3 -80.3 -80.3 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.5 -81.5 -81.5 -81.5 -81.5 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.6 -81.6 -81.6 -81.6 -81.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81 -81 -81 -81 -81 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.6 -81.6 -81.6 -81.6 -81.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.5 -81.5 -81.5 -81.5 -81.5 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.5 -81.5 -81.5 -81.5 -81.5 ...
##   ..$ :List of 1
##   .. ..$ : num [1:7, 1:2] -81.5 -81.5 -81.5 -81.5 -81.5 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.1 -81.1 -81.1 -81.1 -81.1 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.1 -81.1 -81.1 -81.1 -81.1 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.5 -81.5 -81.5 -81.5 -81.5 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.5 -81.5 -81.5 -81.5 -81.5 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.1 -81.1 -81.1 -81.1 -81.1 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.2 -81.2 -81.2 -81.2 -81.2 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.6 -81.6 -81.6 -81.6 -81.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.7 -81.7 -81.7 -81.7 -81.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.6 -81.7 -81.7 -81.6 -81.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:7, 1:2] -81.2 -81.2 -81.2 -81.2 -81.2 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.6 -81.6 -81.6 -81.6 -81.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.2 -81.2 -81.2 -81.2 -81.2 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.5 -81.5 -81.5 -81.5 -81.5 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.5 -81.5 -81.5 -81.5 -81.5 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.5 -81.5 -81.5 -81.5 -81.5 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.6 -81.6 -81.6 -81.6 -81.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:7, 1:2] -81.6 -81.6 -81.6 -81.6 -81.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.6 -81.6 -81.6 -81.6 -81.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.3 -81.3 -81.3 -81.3 -81.3 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.6 -81.6 -81.6 -81.6 -81.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:93, 1:2] -81.7 -81.7 -81.7 -81.7 -81.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.7 -81.7 -81.7 -81.7 -81.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.7 -81.7 -81.7 -81.7 -81.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.7 -81.7 -81.7 -81.7 -81.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.7 -81.7 -81.7 -81.7 -81.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.7 -81.7 -81.7 -81.7 -81.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.6 -81.6 -81.6 -81.6 -81.6 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:25, 1:2] -81.7 -81.7 -81.7 -81.7 -81.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.5 -81.5 -81.5 -81.5 -81.5 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.5 -81.5 -81.5 -81.5 -81.5 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.4 -81.4 -81.4 -81.4 -81.4 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.5 -81.5 -81.5 -81.5 -81.5 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.7 -81.7 -81.7 -81.7 -81.7 ...
##   ..$ :List of 1
##   .. ..$ : num [1:5, 1:2] -81.7 -81.7 -81.7 -81.7 -81.7 ...
##   .. [list output truncated]
##   ..- attr(*, "class")= chr  "XY" "MULTIPOLYGON" "sfg"
##  - attr(*, "sf_column")= chr "geometry"
##  - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA
##   ..- attr(*, "names")= chr  "POINTID" "PSurge05c"</code></pre>
<p>Similar to the wind speed probabilities, storm surge probabilties only has three variables, the <code>POINTID</code>, <code>geometry</code>, and, because we requested the psurge product for 5-feet, <code>PSurge05c</code> (this name changes depending on the product and value).</p>
<p>Note that unlike wind speed probabilities which is a point shapefile, this dataset is a polygon shapefile.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb71-1" data-line-number="1">p <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb71-2" data-line-number="2"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span>(</a>
<a class="sourceLine" id="cb71-3" data-line-number="3">    <span class="dt">data =</span> shp_df<span class="op">$</span>al142016_<span class="dv">2016100706</span>_gt5, </a>
<a class="sourceLine" id="cb71-4" data-line-number="4">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(</a>
<a class="sourceLine" id="cb71-5" data-line-number="5">      <span class="dt">geometry =</span> geometry, </a>
<a class="sourceLine" id="cb71-6" data-line-number="6">      <span class="dt">color =</span> PSurge05c<span class="op">/</span><span class="dv">100</span></a>
<a class="sourceLine" id="cb71-7" data-line-number="7">    ), </a>
<a class="sourceLine" id="cb71-8" data-line-number="8">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb71-9" data-line-number="9"><span class="st">  </span><span class="co"># Show Lake George, FL</span></a>
<a class="sourceLine" id="cb71-10" data-line-number="10"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_segment.html">geom_curve</a></span>(</a>
<a class="sourceLine" id="cb71-11" data-line-number="11">    <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(</a>
<a class="sourceLine" id="cb71-12" data-line-number="12">      <span class="dt">x =</span> <span class="dv">-82</span>, </a>
<a class="sourceLine" id="cb71-13" data-line-number="13">      <span class="dt">y =</span> <span class="dv">28</span>, </a>
<a class="sourceLine" id="cb71-14" data-line-number="14">      <span class="dt">xend =</span> <span class="fl">-81.58</span>, </a>
<a class="sourceLine" id="cb71-15" data-line-number="15">      <span class="dt">yend =</span> <span class="fl">29.2</span></a>
<a class="sourceLine" id="cb71-16" data-line-number="16">    ), </a>
<a class="sourceLine" id="cb71-17" data-line-number="17">    <span class="dt">curvature =</span> <span class="fl">-0.5</span>, </a>
<a class="sourceLine" id="cb71-18" data-line-number="18">    <span class="dt">arrow =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/reexports.html">arrow</a></span>(<span class="dt">length =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/reexports.html">unit</a></span>(<span class="fl">0.01</span>, <span class="st">"npc"</span>))</a>
<a class="sourceLine" id="cb71-19" data-line-number="19">  ) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb71-20" data-line-number="20"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/annotate.html">annotate</a></span>(</a>
<a class="sourceLine" id="cb71-21" data-line-number="21">    <span class="st">"text"</span>, </a>
<a class="sourceLine" id="cb71-22" data-line-number="22">    <span class="dt">x =</span> <span class="fl">-81.5</span>, </a>
<a class="sourceLine" id="cb71-23" data-line-number="23">    <span class="dt">y =</span> <span class="fl">27.9</span>, </a>
<a class="sourceLine" id="cb71-24" data-line-number="24">    <span class="dt">label =</span> <span class="st">"Lake George, FL"</span>, </a>
<a class="sourceLine" id="cb71-25" data-line-number="25">    <span class="dt">size =</span> <span class="dv">3</span></a>
<a class="sourceLine" id="cb71-26" data-line-number="26">  ) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb71-27" data-line-number="27"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">coord_sf</a></span>(</a>
<a class="sourceLine" id="cb71-28" data-line-number="28">    <span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(</a>
<a class="sourceLine" id="cb71-29" data-line-number="29">      <span class="dv">-85</span>, </a>
<a class="sourceLine" id="cb71-30" data-line-number="30">      <span class="dv">-74</span></a>
<a class="sourceLine" id="cb71-31" data-line-number="31">    ), </a>
<a class="sourceLine" id="cb71-32" data-line-number="32">    <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(</a>
<a class="sourceLine" id="cb71-33" data-line-number="33">      <span class="dv">25</span>, </a>
<a class="sourceLine" id="cb71-34" data-line-number="34">      <span class="dv">36</span></a>
<a class="sourceLine" id="cb71-35" data-line-number="35">    ), </a>
<a class="sourceLine" id="cb71-36" data-line-number="36">    <span class="dt">expand =</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb71-37" data-line-number="37">  ) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb71-38" data-line-number="38"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_color_continuous</a></span>(</a>
<a class="sourceLine" id="cb71-39" data-line-number="39">    <span class="dt">name =</span> <span class="st">""</span>, </a>
<a class="sourceLine" id="cb71-40" data-line-number="40">    <span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="fl">0.25</span>, <span class="fl">0.75</span>), </a>
<a class="sourceLine" id="cb71-41" data-line-number="41">    <span class="dt">labels =</span> scales<span class="op">::</span>percent, </a>
<a class="sourceLine" id="cb71-42" data-line-number="42">    <span class="dt">low =</span> <span class="st">"white"</span>, </a>
<a class="sourceLine" id="cb71-43" data-line-number="43">    <span class="dt">high =</span> <span class="st">"red"</span></a>
<a class="sourceLine" id="cb71-44" data-line-number="44">  ) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb71-45" data-line-number="45"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(</a>
<a class="sourceLine" id="cb71-46" data-line-number="46">    <span class="dt">panel.ontop =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb71-47" data-line-number="47">    <span class="dt">panel.background =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span>(),</a>
<a class="sourceLine" id="cb71-48" data-line-number="48">    <span class="dt">panel.grid.major =</span> <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_line</a></span>(<span class="dt">color =</span> <span class="st">"lightgray"</span>, <span class="dt">size =</span> <span class="fl">0.1</span>),</a>
<a class="sourceLine" id="cb71-49" data-line-number="49">    <span class="dt">legend.position =</span> <span class="st">"bottom"</span>, </a>
<a class="sourceLine" id="cb71-50" data-line-number="50">    <span class="dt">legend.box =</span> <span class="st">"vertical"</span></a>
<a class="sourceLine" id="cb71-51" data-line-number="51">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb71-52" data-line-number="52"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span>(<span class="dt">title =</span> <span class="st">"Hurricane Matthew Storm Surge Probabilities (&gt;5ft), Adv #37"</span>)</a></code></pre></div>
<p><img src="gis_data_files/figure-html/psurge-1.png" width="672" style="display: block; margin: auto;"></p>
<p>I took similar steps to creating this plot as I did with wind speed probabilties.</p>
<p>Note what appears to be storm surge well inland from the coast in Lake George, St. Johns River, and elsewhere.</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#build-a-tracking-chart">Build a Tracking Chart</a></li>
      <li>
<a href="#gis-datasets">GIS Datasets</a><ul class="nav nav-pills nav-stacked">
<li><a href="#data-scraping">Data Scraping</a></li>
      <li><a href="#advisory-package">Advisory Package</a></li>
      <li><a href="#forecast-wind-radii">Forecast Wind Radii</a></li>
      <li><a href="#wind-speed-probabilities">Wind Speed Probabilities</a></li>
      <li><a href="#storm-surge-probabilities">Storm Surge Probabilities</a></li>
      </ul>
</li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by <a href="https://timtrice.net">Tim Trice</a>.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
</div>

  
<script src="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.js" integrity="sha256-GKvGqXDznoRYHCwKXGnuchvKSwmx9SRMrZOTh2g4Sb0=" crossorigin="anonymous"></script><script>
  docsearch({
    
    
    apiKey: '5aeb8a5c28f12c523e08f69cf1aab431',
    indexName: 'rrricanes',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>
</body>
</html>
